var LANG_RU = {
    app_description: "StringLOM — визуальный конвейер для текста. Цепочки блоков: Regex, JSON, CSV, sorting. Результат мгновенно, 100% в браузере, без сервера. drag&drop, приватно, без установки.",
    menu_title: "Меню",
    home_page: "Домашняя страница",
    download_latest: "Скачать последний релиз",
    theme_dark: "Темная тема",
    theme_light: "Светлая тема",
    version: "Версия:",
    create: "Создать",
    create_title: "Создать новую цепочку (Alt + N)",
    import: "Импортировать",
    import_title: "Импортировать цепочку (Alt + I)",
    saved_chains: "Сохраненные цепочки",
    toggle_saved: "Свернуть/Развернуть",
    new_chain: "Новая цепочка",
    save: "Сохранить",
    save_title: "Сохранить текущую цепочку (Alt + S)",
    share: "Поделиться",
    share_title: "Поделиться цепочкой",
    export: "Экспортировать",
    export_title: "Экспортировать настройки цепочки (Alt + E)",
    final_result: "Финальный результат",
    download_final: "Скачать результат",
    copy_final: "Копировать результат",
    output_delimiter: "Разделитель при выводе",
    newline: "Новая строка",
    comma: "Запятая",
    semicolon: "Точка с запятой",
    space: "Пробел",
    custom: "Свой...",
    custom_placeholder: "Текст...",
    select_tool: "Выберите инструмент",
    search_tools: "Поиск инструментов (от 2-х символов)...",
    confirmation: "Подтверждение",
    cancel: "Отмена",
    confirm: "Подтвердить",
    input_data: "Ввод данных",
    enter_value: "Введите значение...",
    ok: "ОК",
    attention: "Внимание",
    close: "Закрыть",
    delete_chain_confirm: "Точно удалить сохраненную цепочку?",
    switch_chain_confirm: "Переключиться на другую цепочку? Все несохраненные изменения текущей будут утеряны.",
    new_chain_confirm: "Создать новую цепочку? Все несохраненные изменения текущей будут утеряны.",
    no_saved_chains: "Нет сохраненных",
    delete: "Удалить",
    default_source_text: "Пример строки\nВторая строка\n123",
    block_removed: "Блок удален",
    restore_block: "Восстановить блок",
    add_block: "Добавить блок",
    expand_blocks: "Развернуть блоки",
    collapse_blocks: "Свернуть блоки",
    drag_to_move: "Потяните, чтобы переместить",
    load_from_file: "Загрузить из файла",
    help: "Справка",
    add_block_above: "Добавить блок выше (Alt + B)",
    add_block_below: "Добавить блок ниже (Alt + A)",
    remove_block_alt: "Удалить блок (Alt + Delete)",
    source_placeholder: "Введите текст здесь (или перетащите файл сюда)...",
    line_delimiter: "Разделитель строк",
    lines_count: "Строк:",
    add_without_closing: "Добавить без закрытия",
    created: "Создано",
    saved: "Сохранено",
    exported: "Экспортировано",
    copied: "Скопировано",
    share_error: "Ошибка при создании ссылки",
    copy_clipboard_error: "Не удалось скопировать в буфер обмена. Используйте экспорт в файл или скопируйте вручную.",
    import_prompt: "Вставьте ранее скопированный код цепочки (JSON):",
    invalid_chain_format: "Некорректный формат цепочки",
    import_error: "Ошибка импорта: Неверный формат данных",
    enter_chain_name: "Введите название для этой цепочки:",
    rename_title: "Нажмите, чтобы переименовать (Alt + R)",
    chain_name_placeholder: "Название цепочки...",

    // Categories
    cat_search_clean: "Поиск и очистка",
    cat_remove_filter: "Удаление и фильтрация",
    cat_order_compare: "Порядок и сравнение",
    cat_text_transform: "Трансформация текста",
    cat_formats: "Работа с форматами",
    cat_assembly_templates: "Сборка и шаблоны",
    cat_ai: "AI и LLM",

    // Tools
    tool_regex_title: "Поиск и замена (Regex)",
    tool_regex_desc: "Замена по регулярному выражению",
    tool_regex_pattern: "Регулярное выражение",
    tool_regex_replacement: "Заменить на ($1, $2...)",
    tool_regex_case: "Без учета регистра",
    tool_regex_only_matched: "Оставить только совпадения",
    tool_regex_empty: "Пустой паттерн",

    tool_dedup_title: "Удаление дубликатов",
    tool_dedup_desc: "Оставляет только уникальные строки",
    tool_dedup_trim: "Trim пробелы",

    tool_sort_title: "Сортировка",
    tool_sort_desc: "Сортирует список",
    tool_sort_mode: "Режим",
    tool_sort_text: "Текст",
    tool_sort_numeric: "Числа",
    tool_sort_smart: "Умная (Числа внутри)",
    tool_sort_direction: "Направление",
    tool_sort_asc: "По возрастанию (A-Z)",
    tool_sort_desc: "По убыванию (Z-A)",
    tool_sort_case: "Игнорировать регистр",

    tool_reverse_title: "Разворот (Reverse)",
    tool_reverse_desc: "Переворачивает список строк в обратном порядке",

    tool_compare_title: "Сравнение (Diff)",
    tool_compare_desc: "Сравнить входящий текст со вторым списком",
    tool_compare_list2: "Список для сравнения",
    tool_compare_placeholder: "Строки для сравнения...",
    tool_compare_delimiter: "Разделитель списка",
    tool_compare_show: "Показать",
    tool_compare_common: "Только общие",
    tool_compare_diff: "Только различия (A-B)",
    tool_compare_all: "Все с пометками",

    tool_duplicates_title: "Найти дубликаты",
    tool_duplicates_desc: "Показывает только повторяющиеся строки",
    tool_duplicates_show_counts: "Показывать количество",
    tool_duplicates_none: "(Нет дубликатов)",

    tool_filter_title: "Фильтр строк",
    tool_filter_desc: "Оставить/Удалить строки по условию",
    tool_filter_query: "Текст поиска",
    tool_filter_contains: "Содержит",
    tool_filter_not_contains: "Не содержит",
    tool_filter_starts: "Начинается с",
    tool_filter_ends: "Заканчивается на",

    tool_csv_title: "CSV Парсер",
    tool_csv_desc: "Преобразование CSV в текст по шаблону",
    tool_csv_delimiter: "Разделитель CSV (; или ,)",
    tool_csv_template: "Шаблон ($1, $2...)",
    tool_csv_skip_header: "Пропустить заголовок",

    tool_case_title: "Регистр",
    tool_case_desc: "UPPERCASE, lowercase, Capitalize",
    tool_case_upper: "ВСЕ ЗАГЛАВНЫЕ",
    tool_case_lower: "все строчные",
    tool_case_cap: "Начало Предложения",
    tool_case_word: "Каждое Слово",

    tool_wrapper_title: "Обертка (Prefix/Suffix)",
    tool_wrapper_desc: "Добавить текст в начало/конец каждой строки",
    tool_wrapper_prefix: "Префикс",
    tool_wrapper_suffix: "Суффикс",

    tool_trim_title: "Обрезка (Trim)",
    tool_trim_desc: "Удаляет пробелы с краев каждой строки",
    tool_trim_both: "С обеих сторон",
    tool_trim_left: "Слева",
    tool_trim_right: "Справа",

    tool_ai_cleaner_title: "AI Cleaner",
    tool_ai_cleaner_desc: "Очистка типографики и спецсимволов",
    tool_ai_cleaner_replace: "Заменять мусор на",

    tool_json_format_title: "Форматирование JSON",
    tool_json_format_desc: "Превращает текст в красивый JSON",
    tool_json_format_indent: "Отступ",
    tool_json_format_2spaces: "2 пробела",
    tool_json_format_4spaces: "4 пробела",
    tool_json_format_tab: "Табуляция",
    tool_json_format_minify: "Минифицировать",
    tool_json_format_join: "Разделитель склейки",
    tool_json_format_empty: "Пустой ввод",

    tool_json_path_title: "Извлечение (JSONPath)",
    tool_json_path_desc: "Извлекает элементы из JSON-текста (напр. $.users[*].name)",
    tool_json_path_query: "JSONPath запрос",
    tool_json_path_input_mode: "Входные данные",
    tool_json_path_combined: "Все строки как один JSON",
    tool_json_path_lines: "Каждая строка - отдельный JSON",
    tool_json_path_stringify: "Оборачивать объекты в JSON",
    tool_json_path_lib_error: "Библиотека jsonpath не загружена! Проверьте интернет-соединение.",
    tool_json_path_parse_error: "Ошибка парсинга JSON: ",
    tool_json_path_error: "Ошибка JSONPath: ",

    tool_join_title: "Объединить строки (Join)",
    tool_join_desc: "Собирает список в одну строку",
    tool_join_prefix: "Первые символы",
    tool_join_last_delimiter: "Последний разделитель",
    tool_join_suffix: "Последние символы",
    tool_join_and: " и ",

    tool_split_title: "Разбить строку (Split)",
    tool_split_desc: "Разбивает строки по разделителю",

    tool_add_line_title: "Добавить строку",
    tool_add_line_desc: "Добавляет строки в начало, конец списка и/или между строк",
    tool_add_line_start: "Первая строка",
    tool_add_line_between: "Между строк",
    tool_add_line_end: "Последняя строка",

    tool_template_title: "Шаблонизатор (Nunjucks)",
    tool_template_desc: "Генерация по шаблону (доступны body и lines)",
    tool_template_tpl: "Шаблон Nunjucks (доступны body и lines)",

    tool_js_function_title: "Функция (JS)",
    tool_js_function_desc: "Свой JS код для обработки каждой строки",
    tool_js_function_code: "Код функции (аргумент line)",
    tool_js_function_compilation_error: "Ошибка компиляции: ",

    tool_shuffle_title: "Случайная сортировка",
    tool_shuffle_desc: "Перемешивает строки в случайном порядке",
    tool_shuffle_seed: "Seed (число)",

    tool_to_hex_title: "В HEX (To Hex)",
    tool_to_hex_desc: "Преобразование текста в шестнадцатеричный код",
    tool_to_hex_encoding: "Кодировка",
    tool_to_hex_format: "Формат",
    tool_to_hex_plain: "Слитная строка (xxyyzz)",
    tool_to_hex_spaced: "Через пробел (xx yy zz)",
    tool_to_hex_dump: "Дамп (смещение + 16 байт)",
    tool_to_hex_dump_ascii: "Дамп + ASCII",
    tool_to_hex_uppercase: "Заглавные буквы (A-F)",
    tool_to_hex_error: "Ошибка кодирования: ",

    tool_from_hex_title: "ИЗ HEX (From Hex)",
    tool_from_hex_desc: "Преобразует шестнадцатеричный код обратно в текст",
    tool_from_hex_encoding: "Кодировка байт",
    tool_from_hex_invalid_chars: "Обнаружены недопустимые символы в HEX данных на строке",
    tool_from_hex_incomplete: "Неполный байт (нечетное количество символов) на строке",
    tool_from_hex_not_found: "HEX данные не найдены. Поддерживаемые форматы: \"xx yy zz\", \"xxyyzz\" или дамп \"0000: xx yy zz |ascii|\"",
    tool_from_hex_error: "Ошибка декодирования: ",

    tool_encode_title: "Кодирование (Base64/URL)",
    tool_encode_desc: "Кодирование и декодирование (Base64, URL)",
    tool_encode_mode: "Действие",
    tool_encode_error: "Ошибка: ",

    tool_hash_title: "Хеширование",
    tool_hash_desc: "Вычисляет CRC32, MD5, SHA-1, SHA-256, SHA-384, SHA-512",
    tool_hash_algorithm: "Алгоритм",
    tool_hash_lib_error: "Библиотека CryptoJS не загружена! Проверьте интернет-соединение.",

    tool_debug_title: "Отладка (Debug View)",
    tool_debug_desc: "Визуализирует невидимые символы (пробелы, табы, переносы)",
    tool_debug_spaces: "Показывать пробелы (·)",
    tool_debug_tabs: "Показывать табы (→)",
    tool_debug_numbers: "Номера строк",

    // LLM Tool
    tool_llm_title: "AI Ассистент (LLM)",
    tool_llm_desc: "Обработка текста с помощью больших языковых моделей (Qwen, DeepSeek и др.)",
    tool_llm_provider: "Провайдер",
    tool_llm_model: "Модель",
    tool_llm_api_key: "API Ключ",
    tool_llm_system_prompt: "Системный промпт",
    tool_llm_prompt_tpl: "Шаблон пользовательского промпта",
    tool_llm_batch_processing: "Пакетная обработка",
    tool_llm_batch_size: "Размер пакета (строк)",
    tool_llm_manual_run: "Ручной запуск",
    tool_llm_run_btn: "Запустить AI обработку",
    tool_llm_running: "AI думает...",
    tool_llm_tokens: "Токены:",
    tool_llm_waiting_manual: "Ожидание ручного запуска...",
    tool_llm_auth_required: "Требуется авторизация",
    tool_llm_login_qwen: "Войти через Qwen",
    tool_llm_oauth_code: "Введите этот код на странице chat.qwen.ai/activate:",
    tool_llm_waiting_auth: "Ожидание авторизации...",
    tool_llm_auth_success: "Авторизация прошла успешно!",
    tool_llm_stats_tokens: "Использовано токенов: ",
    tool_llm_stats_prompt: "Промпт: ",
    tool_llm_stats_completion: "Ответ: ",
    tool_llm_error: "Ошибка LLM: ",
    tool_llm_locked: "Выполнение в процессе. Конвейер заблокирован.",

    llm_settings: "Настройки LLM",
    llm_proxy_url: "Base URL прокси",
    llm_proxy_placeholder: "http://127.0.0.1:20000/uuid...",
    run_chain: "Выполнить"
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANG_RU;
}
