var LANG_EN = {
    app_description: "StringLOM — visual text pipeline. Block chains: Regex, JSON, CSV, sorting. Instant results, 100% in-browser, no server. Drag & drop, private, no installation.",
    menu_title: "Menu",
    home_page: "Home Page",
    download_latest: "Download Latest Release",
    theme_dark: "Dark Theme",
    theme_light: "Light Theme",
    version: "Version:",
    create: "Create",
    create_title: "Create new chain (Alt + N)",
    import: "Import",
    import_title: "Import chain (Alt + I)",
    saved_chains: "Saved Chains",
    toggle_saved: "Collapse/Expand",
    new_chain: "New Chain",
    save: "Save",
    save_title: "Save current chain (Alt + S)",
    share: "Share",
    share_title: "Share chain",
    export: "Export",
    export_title: "Export chain settings (Alt + E)",
    ai_assistant: "AI Assistant",
    ai_assistant_title: "AI Assistant",
    ai_assistant_desc: "Describe what kind of data processing pipeline you want to create or modify.",
    ai_prompt_placeholder: "Describe the task or pipeline...",
    ai_welcome_message_new: "Hello! How can I help you build a data processing chain?",
    start: "Starting AI agent...",
    cycle_start: "Starting generation cycle {current} of {max}...",
    generation_start: "Generating processing logic...",
    generation_error: "Error generating structure.",
    execution_start: "Executing generated logic...",
    verification_start: "Verifying results...",
    verification_success: "Chain verification successful!",
    verification_error: "Error during verification.",
    verification_failed: "Verification failed.",
    block_verification_start: "New block detected, starting verification...",
    block_verification_success: "New block verified and added to tools.",
    end: "Processing complete.",
    chain_saved_message: "Chain snapshot saved.",
    chain_restore_title: "Click to restore this version",
    ai_success_message: "Chain updated successfully.",
    chain_show_title: "Click to view the created chain",
    ai_error_prefix: "Error",
    chain_reverted: "Chain restored",
    cancel_changes: "Cancel Changes",
    execute: "Execute",
    final_result: "Final Result",
    download_final: "Download result",
    copy_final: "Copy result",
    output_delimiter: "Output Delimiter",
    newline: "New Line",
    comma: "Comma",
    semicolon: "Semicolon",
    space: "Space",
    custom: "Custom...",
    custom_placeholder: "Text...",
    select_tool: "Select Tool",
    search_tools: "Search tools (2+ characters)...",
    confirmation: "Confirmation",
    cancel: "Cancel",
    confirm: "Confirm",
    input_data: "Data Input",
    enter_value: "Enter value...",
    ok: "OK",
    attention: "Attention",
    close: "Close",
    delete_chain_confirm: "Are you sure you want to delete the saved chain?",
    switch_chain_confirm: "Switch to another chain? All unsaved changes to the current one will be lost.",
    new_chain_confirm: "Create a new chain? All unsaved changes to the current one will be lost.",
    no_saved_chains: "No saved chains",
    delete: "Delete",
    default_source_text: "Example line\nSecond line\n123",
    block_removed: "Block removed",
    restore_block: "Restore block",
    add_block: "Add block",
    expand_blocks: "Expand blocks",
    collapse_blocks: "Collapse blocks",
    drag_to_move: "Drag to move",
    load_from_file: "Load from file",
    help: "Help",
    add_block_above: "Add block above (Alt + B)",
    add_block_below: "Add block below (Alt + A)",
    remove_block_alt: "Remove block (Alt + Delete)",
    source_placeholder: "Enter text here (or drag file here)...",
    line_delimiter: "Line Delimiter",
    lines_count: "Lines:",
    add_without_closing: "Add without closing",
    created: "Created",
    saved: "Saved",
    exported: "Exported",
    copied: "Copied",
    share_error: "Error creating link",
    copy_clipboard_error: "Failed to copy to clipboard. Use export to file or copy manually.",
    import_prompt: "Paste previously copied chain code (JSON):",
    invalid_chain_format: "Invalid chain format",
    import_error: "Import error: Invalid data format",
    enter_chain_name: "Enter a name for this chain:",
    rename_title: "Click to rename (Alt + R)",
    chain_name_placeholder: "Chain name...",

    // Categories
    cat_search_clean: "Search and Clean",
    cat_remove_filter: "Remove and Filter",
    cat_order_compare: "Order and Compare",
    cat_text_transform: "Text Transformation",
    cat_formats: "Work with Formats",
    cat_assembly_templates: "Assembly and Templates",
    cat_ai: "AI & LLM",

    // Tools
    tool_regex_title: "Search and Replace (Regex)",
    tool_regex_desc: "Replace using regular expression",
    tool_regex_pattern: "Regular Expression",
    tool_regex_replacement: "Replace with ($1, $2...)",
    tool_regex_case: "Case insensitive",
    tool_regex_only_matched: "Only matched",
    tool_regex_empty: "Empty pattern",

    tool_dedup_title: "Remove Duplicates",
    tool_dedup_desc: "Keeps only unique lines",
    tool_dedup_trim: "Trim spaces",

    tool_sort_title: "Sort",
    tool_sort_desc: "Sorts the list",
    tool_sort_mode: "Mode",
    tool_sort_text: "Text",
    tool_sort_numeric: "Numeric",
    tool_sort_smart: "Smart (Numbers inside)",
    tool_sort_direction: "Direction",
    tool_sort_asc: "Ascending (A-Z)",
    tool_sort_desc: "Descending (Z-A)",
    tool_sort_case: "Ignore case",

    tool_reverse_title: "Reverse",
    tool_reverse_desc: "Reverses the list of lines",

    tool_compare_title: "Compare (Diff)",
    tool_compare_desc: "Compare incoming text with a second list",
    tool_compare_list2: "List for comparison",
    tool_compare_placeholder: "Lines for comparison...",
    tool_compare_delimiter: "List delimiter",
    tool_compare_show: "Show",
    tool_compare_common: "Only common",
    tool_compare_diff: "Only differences (A-B)",
    tool_compare_all: "All with marks",

    tool_duplicates_title: "Find Duplicates",
    tool_duplicates_desc: "Shows only repeating lines",
    tool_duplicates_show_counts: "Show counts",
    tool_duplicates_none: "(No duplicates)",

    tool_filter_title: "Line Filter",
    tool_filter_desc: "Keep/Remove lines by condition",
    tool_filter_query: "Search text",
    tool_filter_contains: "Contains",
    tool_filter_not_contains: "Does not contain",
    tool_filter_starts: "Starts with",
    tool_filter_ends: "Ends with",

    tool_csv_title: "CSV Parser",
    tool_csv_desc: "Convert CSV to text by template",
    tool_csv_delimiter: "CSV Delimiter (; or ,)",
    tool_csv_template: "Template ($1, $2...)",
    tool_csv_skip_header: "Skip header",

    tool_case_title: "Case",
    tool_case_desc: "UPPERCASE, lowercase, Capitalize",
    tool_case_upper: "UPPERCASE",
    tool_case_lower: "lowercase",
    tool_case_cap: "Sentence Case",
    tool_case_word: "Each Word",

    tool_wrapper_title: "Wrapper (Prefix/Suffix)",
    tool_wrapper_desc: "Add text to the beginning/end of each line",
    tool_wrapper_prefix: "Prefix",
    tool_wrapper_suffix: "Suffix",

    tool_trim_title: "Trim",
    tool_trim_desc: "Removes spaces from the edges of each line",
    tool_trim_both: "Both sides",
    tool_trim_left: "Left side",
    tool_trim_right: "Right side",

    tool_ai_cleaner_title: "AI Cleaner",
    tool_ai_cleaner_desc: "Cleanup typography and special characters",
    tool_ai_cleaner_replace: "Replace junk with",

    tool_json_format_title: "JSON Formatting",
    tool_json_format_desc: "Turns text into pretty JSON",
    tool_json_format_indent: "Indent",
    tool_json_format_2spaces: "2 spaces",
    tool_json_format_4spaces: "4 spaces",
    tool_json_format_tab: "Tabulation",
    tool_json_format_minify: "Minify",
    tool_json_format_join: "Join delimiter",
    tool_json_format_empty: "Empty input",

    tool_json_path_title: "Extraction (JSONPath)",
    tool_json_path_desc: "Extracts elements from JSON text (e.g. $.users[*].name)",
    tool_json_path_query: "JSONPath query",
    tool_json_path_input_mode: "Input data",
    tool_json_path_combined: "All lines as one JSON",
    tool_json_path_lines: "Each line as separate JSON",
    tool_json_path_stringify: "Wrap objects in JSON",
    tool_json_path_lib_error: "JSONPath library not loaded! Check internet connection.",
    tool_json_path_parse_error: "JSON parse error: ",
    tool_json_path_error: "JSONPath error: ",

    tool_join_title: "Join Lines",
    tool_join_desc: "Assembles list into a single string",
    tool_join_prefix: "First characters",
    tool_join_last_delimiter: "Last delimiter",
    tool_join_suffix: "Last characters",
    tool_join_and: " and ",

    tool_split_title: "Split String",
    tool_split_desc: "Splits lines by delimiter",

    tool_add_line_title: "Add Line",
    tool_add_line_desc: "Adds lines to the beginning, end of the list and/or between lines",
    tool_add_line_start: "First line",
    tool_add_line_between: "Between lines",
    tool_add_line_end: "Last line",

    tool_template_title: "Templatizer (Nunjucks)",
    tool_template_desc: "Generation by template (body and lines available)",
    tool_template_tpl: "Nunjucks template (body and lines available)",

    tool_js_function_title: "Function (JS)",
    tool_js_function_desc: "Custom JS code for each line processing (argument 'line')",
    tool_js_function_code: "Function code (argument 'line')",
    tool_js_function_compilation_error: "Compilation error: ",

    tool_shuffle_title: "Random Shuffle",
    tool_shuffle_desc: "Shuffles lines in random order",
    tool_shuffle_seed: "Seed (number)",

    tool_to_hex_title: "To HEX",
    tool_to_hex_desc: "Convert text to hexadecimal code",
    tool_to_hex_encoding: "Encoding",
    tool_to_hex_format: "Format",
    tool_to_hex_plain: "Plain string (xxyyzz)",
    tool_to_hex_spaced: "With spaces (xx yy zz)",
    tool_to_hex_dump: "Dump (offset + 16 bytes)",
    tool_to_hex_dump_ascii: "Dump + ASCII",
    tool_to_hex_uppercase: "Uppercase letters (A-F)",
    tool_to_hex_error: "Encoding error: ",

    tool_from_hex_title: "From HEX",
    tool_from_hex_desc: "Convert hexadecimal code back to text",
    tool_from_hex_encoding: "Byte encoding",
    tool_from_hex_invalid_chars: "Invalid characters detected in HEX data on line",
    tool_from_hex_incomplete: "Incomplete byte (odd number of characters) on line",
    tool_from_hex_not_found: "HEX data not found. Supported formats: \"xx yy zz\", \"xxyyzz\" or dump \"0000: xx yy zz |ascii|\"",
    tool_from_hex_error: "Decoding error: ",

    tool_encode_title: "Encoding (Base64/URL)",
    tool_encode_desc: "Encoding and decoding (Base64, URL)",
    tool_encode_mode: "Action",
    tool_encode_error: "Error: ",

    tool_hash_title: "Hashing",
    tool_hash_desc: "Calculates CRC32, MD5, SHA-1, SHA-256, SHA-384, SHA-512",
    tool_hash_algorithm: "Algorithm",
    tool_hash_lib_error: "CryptoJS library not loaded! Check internet connection.",

    tool_debug_title: "Debug View",
    tool_debug_desc: "Visualizes invisible characters (spaces, tabs, breaks)",
    tool_debug_spaces: "Show spaces (·)",
    tool_debug_tabs: "Show tabs (→)",
    tool_debug_numbers: "Line numbers",

    // LLM Tool
    tool_llm_title: "AI Assistant (LLM)",
    tool_llm_desc: "Processing text using Large Language Models (Qwen, DeepSeek, etc.)",
    tool_llm_provider: "Provider",
    tool_llm_model: "Model",
    tool_llm_api_key: "API Key",
    tool_llm_system_prompt: "System Prompt",
    tool_llm_prompt_tpl: "User Prompt Template",
    tool_llm_batch_processing: "Batch processing",
    tool_llm_batch_size: "Batch size (lines)",
    tool_llm_manual_run: "Manual Execution",
    tool_llm_run_btn: "Run AI Processing",
    tool_llm_running: "AI is thinking...",
    tool_llm_tokens: "Tokens:",
    tool_llm_waiting_manual: "Waiting for manual run...",
    tool_llm_auth_required: "Authorization required",
    tool_llm_login_qwen: "Login with Qwen",
    tool_llm_oauth_code: "Enter this code at chat.qwen.ai/activate:",
    tool_llm_waiting_auth: "Waiting for authorization...",
    tool_llm_auth_success: "Successfully authorized!",
    tool_llm_stats_tokens: "Tokens used: ",
    tool_llm_stats_prompt: "Prompt: ",
    tool_llm_stats_completion: "Completion: ",
    tool_llm_error: "LLM Error: ",
    tool_llm_locked: "Execution in progress. Pipeline is locked.",

    llm_settings: "LLM Settings",
    llm_proxy_url: "Proxy Base URL",
    llm_proxy_placeholder: "http://127.0.0.1:20000/uuid...",
    run_chain: "Execute",

    tool_regex_long_desc: "Search and replace operations are performed based on regular expressions that allow finding complex character sequences. The input field for the pattern accepts standard syntax to identify required fragments in each line. The case-insensitive option helps find matches regardless of whether letters are written as uppercase or lowercase. If data modification is required, a replacement string field is used where capture group references can be applied. The only matched mode is useful when extracting specific identifiers from system logs. The tool processes input data line by line, applying specified rules to each element of the list. When processing logs, you can isolate only timestamps or error codes, cutting off unnecessary information. Disabling the replacement mode turns the block into a content search tool. Correct template composition ensures precise data isolation in complex string structures. In case of a syntax error in the expression, the system will display a notification to adjust the rules. Approach flexibility allows solving tasks ranging from simple typo correction to data structure restructuring. Global search flags are applied for text work, ensuring processing of all occurrences. The work result is passed to the next link in the chain for further transformations. Using group references in the replacement string enables changing the order of elements within a line. This simplifies reformatting network address lists or changing date formats in reports. Processing is performed entirely on the user side, which is important when working with confidential configuration files.",
    tool_deduplicate_long_desc: "Removing duplicates ensures data cleanliness by excluding repeating elements from the overall list. The algorithm compares each line with already processed ones and keeps only the first occurrence of a unique value. The preliminary edge cleaning checkbox allows ignoring extra spaces when comparing lines. This is critical when processing email lists or usernames where accidental indents might prevent duplicate detection. The tool effectively handles cleaning large datasets obtained from various sources. After completion, the system provides statistics on the number of removed elements and the final list size. The sequence of unique lines is preserved exactly as they were encountered in the source file. This allows using the tool for preparing clean mailing lists or databases. When analyzing access logs, removing repeats helps isolate unique visitor IP addresses. In the case of working with program code, the block helps get rid of redundant imports or repeating settings. The trimming option guarantees that lines with identical text but different space counts will be considered identical. The cleaning result is ready for further sorting or export to other formats. Absence of hidden characters after processing increases the reliability of subsequent pipeline stages. Working with the list in browser memory ensures high speed even with a significant number of records. Each unique record remains in a single copy to ensure output data compactness. Using this tool is key to the correct operation of all analytical systems of the enterprise.",
    tool_sort_long_desc: "Sorting organizes the list of lines according to selected criteria and comparison rules. Several modes are available, including text order, numeric comparison, and a smart algorithm. Text mode is suitable for regular lists where word letter sequence is important. Numeric sorting correctly handles values by treating them as numbers rather than a set of characters. Smart mode allows correctly ranking strings containing both text and numbers, such as version numbers or filenames. Direction selection allows arranging elements in ascending or descending order. The case sensitivity toggle determines whether uppercase letters will take priority over lowercase when determining order. This is useful when preparing lists of function names or variables in source code. Processing ignores empty lines to improve final result readability. Using local settings guarantees correct behavior for different languages and alphabets. When working with logs, sorting helps line up events in chronological order or by criticality level. In address lists, you can quickly find required records grouped alphabetically. The tool creates a new ordered data array without changing the structure of the lines themselves. High algorithm performance allows processing thousands of records almost instantly. After applying parameters, the list is passed further down the chain for possible filtering or formatting.",
    tool_reverse_long_desc: "List reversal changes the sequence of all lines to the exact opposite without changing their internal content. The first element becomes the last, and the last takes the place at the very beginning of the list. The tool has no additional configuration parameters, ensuring its simple and predictable operation. This action is often applied after sorting when an inverse data sequence is required. When analyzing logs sorted in forward order, reversal allows seeing the most recent entries at the top. The block effectively works with any types of textual information, from identifier lists to code snippets. The entire data array is processed as a whole, preserving the integrity of each individual line. This is useful when needing to change data processing logic in the pipeline. In a transformation chain, reversal can serve as a preparatory step for extracting specific fragments. The conversion result is immediately displayed and ready for transfer to the next block. The operation is performed in a single pass, which guarantees minimal computational resource costs. Absence of settings excludes configuration errors when using the tool. This action is a classic tool for list manipulation in system administration tasks. Saving the final result allows fixing the modified order for further use. Applying this tool is a standard step in preparing data for visual monitoring dashboards.",
    tool_compare_long_desc: "List comparison allows identifying differences or common elements between the main text and an additional set of lines. The second input field is intended for pasting the list against which the comparison will be made. The delimiter setting determines exactly how data in the second list will be split for correct comparison. The user can choose a mode to display only common elements present in both sets. Also available is a difference output mode showing lines present in the first list but absent in the second. For full analysis, a mode for displaying all lines with marks about their presence in each list is provided. This is indispensable when synchronizing databases or checking allowed address lists. The tool automatically cleans line edges of extra spaces to improve matching precision. When processing configuration files, you can quickly find missing or redundant parameters. The result is output as a new list matching the selected filtering criterion. Comparison of large data volumes occurs quickly due to the use of efficient search algorithms. Statistics at the bottom of the block show the number of resulting lines. The tool helps control data integrity when moving information between different systems. Using special prefixes in the show-all-lines mode allows visually distinguishing added and removed records. Automating the matching process eliminates human error when checking long compliance lists.",
    tool_duplicates_long_desc: "Duplicate search focuses user attention only on those lines that occur in the text more than once. Unlike duplicate removal, this tool hides unique values, leaving only repeating data. The option to show repetition counts adds a numeric value in parentheses to each found line. This allows quickly assessing the scale of redundancy in the processed data array. The tool is useful when auditing security logs to identify suspiciously frequent events. In inventory lists, searching for repeats helps find entry errors or duplicate product records. Processing is performed with automatic edge space removal to exclude false differences. If no duplicates are found, the system will output a corresponding information message. The search result is a compact list of only problematic elements. This simplifies manual verification and subsequent data cleaning in source systems. The tool works quickly even on lists containing tens of thousands of records. Obtained data can be copied or passed further down the pipeline for additional processing. Using this block is an important stage in the data quality assurance process in corporate systems. Identifying repeating user identifiers helps prevent database conflicts. Analysis results can be used to optimize data storage volume in corporate repositories.",
    tool_filter_long_desc: "Line filtering allows keeping or removing text fragments based on a given condition and keyword. The text to be checked for presence in each line of the list is entered into the query input field. Several operation modes are available, including searching by occurrence, excluding matches, as well as checking the beginning or end of a line. Contains mode keeps only those lines where the specified character sequence is present. The exclude option works inversely, removing all records matching the condition and leaving the rest. Checking the beginning of a line is useful for isolating specific log types starting with a date stamp or importance level. Ends-with mode helps find files with specific extensions or records ending with special markers. The tool does not consider character case during comparison, which simplifies search setup. This is an efficient way to quickly reduce the processed data volume to the required minimum. When analyzing network reports, filtering helps isolate traffic from specific IP addresses. In the process of list cleaning, you can easily remove lines containing unwanted marks or comments. Filtering results are immediately ready for further transformations in the block chain. Statistics display the number of matches and the number of lines removed from the list. The tool provides high flexibility when working with unstructured text arrays. Applying filters significantly speeds up the process of finding a needle in a haystack when working with raw data.",
    tool_csv_long_desc: "CSV data parsing is designed to transform structured tabular lines into an arbitrary text format according to a given template. The delimiter selection field allows specifying the character used to separate columns, such as a semicolon or comma. The template field defines the future line structure, where column sequence numbers are denoted by special characters with digits. The skip header option allows ignoring the first line of the file if it contains column names. The tool automatically splits each incoming line into components and substitutes them into specified template locations. This is convenient for generating SQL queries, configuration files, or formatted reports from database exports. When processing a user list, you can turn a table with names and emails into a set of commands for creating accounts. Each column is cleaned of extra spaces before substitution to ensure a neat result. If a column number not present in the source line is specified in the template, an empty string will be substituted in its place. The tool effectively works with large exports in CSV format, providing instant results. Transformed data is saved as a list of lines ready for further processing by other blocks. Template configuration flexibility allows implementing complex formatting rules without writing code. Using this block significantly speeds up routine data migration tasks between systems. The tool is indispensable when working with bank statements or payment registries. Each output line can be supplemented with static text to explain the data structure.",
    tool_case_long_desc: "Letter case modification allows quickly bringing text data to a single writing standard. Several transformation modes are available, including converting all characters to uppercase or lowercase. The sentence case mode automatically corrects text, making the first letter after a period large. The each word case option makes the first letter of every word uppercase, which is useful for titles or names. The tool correctly handles Cyrillic and Latin alphabets, considering alphabet specifics. When processing variable lists in program code, bringing them to a single case helps avoid naming errors. In databases, normalizing user name case ensures uniformity and simplifies subsequent searching. The block processes each line independently, preserving the original list structure. This is a quick way to fix careless data entry in web forms or during import from different sources. Using lowercase is often required when preparing data for subsequent comparison or duplicate searching. The tool does not add or remove characters, changing only their typeface. The work result is visible instantly and can be passed to subsequent pipeline links. Setup simplicity makes this block indispensable when preparing text reports. High processing speed guarantees absence of delays even when working with very long lists. Correct case is important for the professional appearance of documentation and technical correspondence.",
    tool_wrapper_long_desc: "Line wrapping adds arbitrary text to the beginning and end of each line in the processed list. Text that should appear before the original line content is entered into the prefix field. The suffix field is intended for characters that will be added at the very end. The tool is useful for turning a regular word list into a set of array elements for program code. You can easily add quotes around each line and a comma at the end for use in JSON or JavaScript configuration files. When forming SQL queries, the wrapper helps add required command parts around identifiers. The block works with all incoming lines without exception, preserving their order. This significantly speeds up the process of preparing data for insertion into other systems or documents. If one of the fields is left empty, addition will be performed only on one side. The tool does not change the original text inside the line, acting only on its boundaries. When processing file paths, you can quickly add a root directory to all records. The formatting result is passed further down the chain for possible joining or filtering. Operation simplicity and clarity make this block one of the most frequently used during data assembly. Wrapping saves time by eliminating the need to manually edit each line in a text editor. Wrapping allows quickly turning plain text into elements of structured program code.",
    tool_trim_long_desc: "Space trimming removes invisible characters from the edges of each line in the list. Modes for removing whitespace from both sides, only left, or only right are available. Spaces, tab characters, and other non-printing characters that might interfere with processing are subject to removal. The tool is essential when cleaning data after copying from tables or documents where extra indents often occur. Removing spaces from the left aligns text to the left edge, which is useful for formatting program code. Trimming from the right helps get rid of invisible junk that might lead to errors in line comparison logic. The tool keeps statistics of modified lines, allowing assessment of the number of cleaned records. The block processes each line individually without affecting the main text inside. This is a mandatory stage before duplicate searching or list comparison to ensure result accuracy. Clean data takes up less space and looks professional in final reports. When processing email addresses or logins, trimming prevents authorization errors due to accidental spaces. The tool works lightning fast, providing instant cleaning of huge text arrays. The obtained result guarantees the absence of hidden problems when transferring data to other systems. Compactness and reliability make trimming an important link in any text processing pipeline. Data cleanliness at the input guarantees the predictability of all subsequent processing algorithms.",
    tool_ai_cleaner_long_desc: "Cleaning text of special characters and typography is designed for normalizing line content. The tool automatically replaces various types of long dashes with standard hyphens and converts curly quotes into straight ones. Furthermore, the algorithm removes all characters that do not belong to letters, digits, spaces, or standard punctuation marks. A replacement string can be specified in the field, which will substitute all found text junk. This allows preparing data for import into systems that do not support extended character sets. The tool is particularly useful when processing texts copied from word processors or web pages with complex layout. Cleaning helps avoid encoding problems when saving files or transferring data through network protocols. The block provides detailed statistics on the number of removed characters during the process. Each line of the list passes through the filter while preserving the overall document structure. Using this tool guarantees that no hidden control codes or non-standard signs remain in the text. When preparing configuration files, this helps ensure their readability by parsers. The work result is a clean text consisting of an allowed set of characters. High operation speed allows processing large information volumes without delays. Data normalization increases the operational stability of the entire processing chain. Using this block helps avoid errors when parsing data with third-party tools.",
    tool_json_format_long_desc: "JSON formatting transforms input text into a structured and easily readable form with correct indentation. The tool supports choosing indentation size, including two or four spaces, as well as using a tab character. To reduce data size, a minification mode is provided that removes all extra spaces and line breaks. The block allows joining incoming lines into a single text before parsing using a customizable delimiter. This is useful when a JSON object is split into several parts or passed as individual log lines. In case syntax errors are detected in the source code, the tool will output a message describing the problem and indicating the position. Correct formatting is essential for analyzing complex data structures and debugging program interfaces. The tool turns an unreadable text string into a beautiful object tree. When working with configurations, this helps visually control parameter nesting. The entire process occurs locally in the browser, which guarantees the security of processed information. The result is split into separate lines for convenience of subsequent processing by other blocks. Statistics at the bottom show the total number of lines in the final JSON file. The block effectively handles objects of any complexity and nesting level. Using formatting significantly increases the convenience of team development when exchanging data fragments. Formatted data view facilitates its perception during security audits of systems.",
    tool_json_path_long_desc: "Data extraction using JSONPath allows selecting specific elements from complex data structures based on special queries. The path to required values is specified in the query input field using standard syntax with dots and brackets. The tool supports two modes of working with input data: processing the entire text as a single object or analyzing each line as a separate JSON. Combined mode is suitable for large files, while line-by-line analysis is indispensable when parsing logs where each record is an independent object. An additional option allows converting extracted objects back into JSON text format to preserve structure. If the query processing library is not loaded, the system will output a corresponding warning. The tool helps quickly pull lists of identifiers, prices, or names from voluminous program interface responses. Upon occurrence of parsing or query execution errors, the user will receive a detailed notification. Selection results are combined into a new list of lines ready for further use. This is a powerful means for automating information collection without needing to write complex scripts. Selection can include filtering by conditions directly inside the JSONPath query. Using this block significantly simplifies the work of system analysts when parsing data. High performance guarantees fast processing even when using complex search templates. This allows integrating the block into complex automated report processing systems. Using filters within the path helps select only those objects that meet certain quality criteria.",
    tool_join_long_desc: "Line joining assembles all elements of the incoming list into a single overall string using specified rules. A prefix can be specified in the settings to be added at the very beginning of the final text. The main delimiter is inserted between all lines, helping structure the data. An additional last delimiter parameter allows using a special word or character before the final element of the list. This is useful for creating naturally readable sentences, for example with the word and at the end. A suffix is added at the conclusion of the entire resulting line, closing the text block. The tool is often applied for generating commands, parameter lists, or code snippets. When processing a name list, you can easily turn it into a string for insertion into a report or letter. The block correctly handles empty lists by returning an empty string. If there is only one element in the list, delimiters are not applied; only prefix and suffix are used. This action is the concluding stage when assembling data from many small fragments. The joining result is output as one long string convenient for copying. High operation speed is ensured by an efficient concatenation algorithm in browser memory. The tool allows flexibly configuring the joining format for any applied tasks. The tool provides high flexibility when forming final text blocks for reports.",
    tool_split_long_desc: "Line splitting breaks each incoming line into several new elements based on a specified delimiter character. A character or character sequence at which the text will be cut is specified in the parameter input field. This action is inverse to joining and is often used to prepare data for subsequent filtering or sorting. For example, a line with a comma-separated identifier list can be turned into a convenient vertical column. The tool processes the entire data array, increasing the total number of lines in the list. This is useful when parsing file paths when folders and filenames need to be separated. When processing logs, splitting helps isolate individual fields from one long record. The block works quickly and does not require complex setup to achieve results. after splitting, each new line becomes an independent element of the processing pipeline. This allows applying individual transformation rules to them, such as case change or space trimming. The tool automatically keeps count of the number of resulting lines after performing the operation. The entire splitting process occurs instantly, which is important for interactive work. The obtained result provides more granular control over data in the processing chain. Splitting complex strings into constituent parts significantly simplifies subsequent data search and matching. The tool supports using multi-character sequences as partition boundaries.",
    tool_add_line_long_desc: "Adding lines allows inserting arbitrary text into fixed positions of the data list. Text that will be added at the very beginning of the final array is entered into the first line field. The between lines parameter ensures insertion of specified text after each existing element except the last one. This is useful for separating data with visual markers or adding empty lines for readability. The last line field is intended for text that will conclude the entire list. The tool helps format data blocks by adding headers and footers to reports. When preparing lists for insertion into program code, opening and closing brackets can be added. The tool does not change the content of the lines themselves, acting only on the list structure. This is a quick way to supplement a data array with necessary service information. If fields are left empty, corresponding additions will not be made. The block preserves the sequence order of original data, ensuring a predictable result. When forming mailing lists, a greeting and signature can be added to the entire address set. The work result is immediately displayed in the interface and ready for export. Using this tool eliminates the need for manual editing of the beginning and end of large files. Adding service lines helps visually structure the result for human readability.",
    tool_template_long_desc: "A templating engine based on the Nunjucks engine provides powerful capabilities for generating text by complex rules. Variables, loops, and conditional operators can be used in the template field to form the final result. The tool provides access to two main variables: the entire text as a whole and the list of individual lines. This allows creating repeating data structures such as HTML lists or XML documents. Templates support filters for transforming data directly during the generation process. The tool is ideal for creating emails from an address list or forming complex configuration files. Upon detection of errors in template syntax, the system will output a detailed message for debugging. Engine flexibility allows implementing logic unavailable to simple replacement blocks. The entire template rendering process occurs on the client side, ensuring high data privacy. Output data is split by lines for compatibility with other pipeline blocks. This is an advanced tool for professional work with text arrays. The templator saves time when creating uniform documents based on structured data. The ability to use loops allows traversing lists of any length with minimal effort. The work result always matches the structure specified in the template. Using templates turns simple text processing into a powerful document automation tool.",
    tool_js_function_long_desc: "A custom JS function allows implementing arbitrary text processing logic for each line of the list. The body of the function, which receives an argument with the current line and must return the modified value, is written in the code input field. This gives unlimited possibilities for data transformation, from mathematical calculations to complex line parsing. In case errors occur during script execution, the tool will mark problematic lines with a corresponding notification. The block is useful when standard tools are insufficient for solving a specific task. Any built-in JavaScript methods for working with strings, arrays, and numbers can be used. The tool automatically applies the written code to each element of the input list. This allows quickly processing data with complex logic specific to a particular project. When preparing data, you can extract parts of lines, swap them, or perform condition checks. High flexibility makes this block indispensable for developers and system administrators. Using a function ensures full control over the conversion process of each record. All code is executed in the user's secure browser environment. The processing result is immediately passed to the next element of the chain for final assembly. Professional users can use this block to implement complex encryption or hashing algorithms on the fly. Every change is instantly reflected in the final result, allowing real-time logic debugging.",
    tool_shuffle_long_desc: "Random sorting shuffles the list lines in an arbitrary order using a permutation algorithm. The tool is equipped with a field for entering a numeric seed, which determines the sequence of random numbers. Using the same seed value allows obtaining an identical shuffling result in repeated runs. If the field is left empty, the system will automatically generate a random number during block initialization. This is useful for creating random samples from large data arrays for testing. When preparing task or question lists, random order helps avoid bias. The tool processes all list lines without changing their internal content. Shuffling occurs quickly even for very long address lists or logs. The block guarantees uniform distribution of elements throughout the final list. The result can be fixed by saving the seed value in the chain settings. This is an indispensable tool for conducting surveys, distributing resources, or creating game datasets. The shuffled list is ready for further filtering or formatting. Control simplicity and predictability when using a seed make this block a reliable assistant. Each click of the refresh button with an empty seed creates a completely new line sequence. Absence of patterns in the final list helps conduct fair and unbiased system tests.",
    tool_to_hex_long_desc: "Converting text to hexadecimal code allows representing data as a byte sequence. A character encoding can be chosen in the settings, including the universal UTF-8 format and specific encodings for Cyrillic such as Windows-1251 or KOI8-R. Several output formats are available, from a continuous string to a detailed dump with offsets. Spaced mode between bytes is convenient for visual analysis of data structure. The dump format adds a column with text representation of bytes, which helps identify information fragments. The option to use uppercase letters allows configuring the appearance of hexadecimal values. The tool is indispensable when debugging network protocols and analyzing binary files. Processing of each line occurs independently, allowing comparison of byte representation of different records. In case of encoding errors, the system will output a warning describing the problem. This is a professional means for studying the internal representation of characters in various systems. The result can be used for insertion into program code or transfer to debuggers. High conversion precision guarantees data correctness at a low level. Using various encodings helps identify text display problems in older systems. The option to display a dump with ASCII insertion allows visually correlating bytes with their text equivalents. This significantly speeds up the search for header structures in unknown data formats.",
    tool_from_hex_long_desc: "Conversion from hexadecimal code back to text restores original content based on byte data. The user can choose the byte encoding to be used during decoding, ensuring correct character display. The tool automatically recognizes various input formats, including continuous sequences, space-separated values, and classic dumps with offsets. During processing, checks for presence of invalid characters and completeness of byte pairs are performed. If errors are found in the data, the system will indicate the line number and problem type for quick correction. The block is useful for reading encrypted logs, analyzing memory dumps, or restoring data from network captures. Restored text is split into lines, allowing continued processing with standard tools. The tool effectively handles Windows-1251, CP866, and KOI8-R encodings, which is important for working with legacy systems. High algorithm reliability guarantees accurate restoration of every byte of information. If HEX data is not found in the input stream, a corresponding notification will be output. This is a powerful means for system engineers and security specialists. The decoding process occurs instantly, turning unreadable digits into understandable text. This allows restoring damaged text files saved in incorrect encodings. Each processed line returns to the text stream for potential further filtering or searching. The tool ensures high precision when working with low-level technical data.",
    tool_encode_long_desc: "Data encoding and decoding supports popular text conversion formats such as Base64 and URL encoding. A specific action is chosen in the settings: packing into a secure format for transmission or restoring original text. Base64 encoding is often applied for transmitting binary data or special characters through text protocols. URL encoding is necessary when preparing parameters for web requests, ensuring replacement of spaces and special characters with safe sequences. The tool processes each list line individually, which is convenient when preparing sets of links or identifiers. In case of errors when processing incorrect input data, the system will output a message with an explanation. The block guarantees preservation of information integrity when moving between different transmission environments. The conversion result remains as a list of lines for further use in the pipeline. This is a fast and reliable way to prepare data for integration with external web services. High operation speed allows processing thousands of lines per second. Using this block eliminates the need to use third-party online converters. Processing security is ensured by the absence of data transfer to the server. The tool is useful when forming configuration files requiring a secure representation of control characters. Automatic processing of each line eliminates the need to use external scripts for mass encoding. The work result is fully compatible with all modern web data transmission standards.",
    tool_hash_long_desc: "Calculating hash sums allows obtaining unique digital fingerprints for each text line. A wide selection of algorithms is available, including classic MD5 and SHA-1, as well as modern and secure SHA-256 and SHA-512. For simple integrity control tasks, the fast CRC32 algorithm is provided. The tool automatically applies the chosen encoding method to all lines of the input list. This is indispensable when checking file integrity, comparing passwords, or creating unique keys for databases. The block requires presence of a special library, and in case of problems with its loading, the user will receive a notification. The calculation result is represented as a string of letters and digits characteristic of the chosen algorithm. Hashing is performed on the user side, which is critical for working with confidential passwords. Obtained values can be used to find duplicates in large data arrays by their short fingerprints. Operation speed is optimized for fast processing of long lists. The tool helps automate data verification tasks in system administration. Every change in the source line leads to a complete change of the final hash. This allows for quick indexing of large arrays of text information for subsequent retrieval. Using different algorithms helps select the optimal balance between calculation speed and collision resistance. The tool provides a reliable way to monitor data immutability during storage.",
    ai_allow_new_blocks: "Allow creating new blocks",
    view_source_title: "View Source Code",
    tool_debug_view_long_desc: "Debug mode visualizes hidden text elements such as spaces, tab characters, and line breaks. This allows seeing the document structure, which is usually hidden from the user's eyes when reading. Markers for each type of invisible character can be enabled in the settings. The line numbering option helps quickly navigate large configuration files or long logs. The tool does not change original data, acting exclusively as a visualization layer. This is critically important when searching for causes of parsing errors caused by extra spaces or incorrect breaks. The block displays the first fifty lines to ensure high interface performance. Visualization helps distinguish a tab from a set of spaces, which is important for files with rigid indentation structure. Statistics in the block show the total number of found special characters of various types. When working with data obtained from questionable sources, debugging helps quickly identify junk characters. This is a professional tool for text quality control before its final use. Representation transparency increases confidence in the correctness of the entire processing chain. The block is ideal for final result verification before export to critical systems. The block allows seeing extra carriage return characters that often cause errors in scripts. Using debug view is the gold standard when preparing data for mission-critical systems."
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANG_EN;
}
