var LANG_EN = {
    app_description: "StringLOM — visual text pipeline. Block chains: Regex, JSON, CSV, sorting. Instant results, 100% in-browser, no server. Drag & drop, private, no installation.",
    menu_title: "Menu",
    home_page: "Home Page",
    download_latest: "Download Latest Release",
    theme_dark: "Dark Theme",
    theme_light: "Light Theme",
    version: "Version:",
    create: "Create",
    create_title: "Create new chain (Alt + N)",
    import: "Import",
    import_title: "Import chain (Alt + I)",
    saved_chains: "Saved Chains",
    toggle_saved: "Collapse/Expand",
    new_chain: "New Chain",
    save: "Save",
    save_title: "Save current chain (Alt + S)",
    share: "Share",
    share_title: "Share chain",
    export: "Export",
    export_title: "Export chain settings (Alt + E)",
    final_result: "Final Result",
    download_final: "Download result",
    copy_final: "Copy result",
    output_delimiter: "Output Delimiter",
    newline: "New Line",
    comma: "Comma",
    semicolon: "Semicolon",
    space: "Space",
    custom: "Custom...",
    custom_placeholder: "Text...",
    select_tool: "Select Tool",
    search_tools: "Search tools (2+ characters)...",
    confirmation: "Confirmation",
    cancel: "Cancel",
    confirm: "Confirm",
    input_data: "Data Input",
    enter_value: "Enter value...",
    ok: "OK",
    attention: "Attention",
    close: "Close",
    delete_chain_confirm: "Are you sure you want to delete the saved chain?",
    switch_chain_confirm: "Switch to another chain? All unsaved changes to the current one will be lost.",
    new_chain_confirm: "Create a new chain? All unsaved changes to the current one will be lost.",
    no_saved_chains: "No saved chains",
    delete: "Delete",
    default_source_text: "Example line\nSecond line\n123",
    block_removed: "Block removed",
    restore_block: "Restore block",
    add_block: "Add block",
    expand_blocks: "Expand blocks",
    collapse_blocks: "Collapse blocks",
    drag_to_move: "Drag to move",
    load_from_file: "Load from file",
    help: "Help",
    add_block_above: "Add block above (Alt + B)",
    add_block_below: "Add block below (Alt + A)",
    remove_block_alt: "Remove block (Alt + Delete)",
    source_placeholder: "Enter text here (or drag file here)...",
    line_delimiter: "Line Delimiter",
    lines_count: "Lines:",
    add_without_closing: "Add without closing",
    created: "Created",
    saved: "Saved",
    exported: "Exported",
    copied: "Copied",
    share_error: "Error creating link",
    copy_clipboard_error: "Failed to copy to clipboard. Use export to file or copy manually.",
    import_prompt: "Paste previously copied chain code (JSON):",
    invalid_chain_format: "Invalid chain format",
    import_error: "Import error: Invalid data format",
    enter_chain_name: "Enter a name for this chain:",
    rename_title: "Click to rename (Alt + R)",
    chain_name_placeholder: "Chain name...",

    // Categories
    cat_search_clean: "Search and Clean",
    cat_remove_filter: "Remove and Filter",
    cat_order_compare: "Order and Compare",
    cat_text_transform: "Text Transformation",
    cat_formats: "Work with Formats",
    cat_assembly_templates: "Assembly and Templates",
    cat_ai: "AI & LLM",

    // Tools
    tool_regex_title: "Search and Replace (Regex)",
    tool_regex_desc: "Replace using regular expression",
    tool_regex_pattern: "Regular Expression",
    tool_regex_replacement: "Replace with ($1, $2...)",
    tool_regex_case: "Case insensitive",
    tool_regex_only_matched: "Only matched",
    tool_regex_empty: "Empty pattern",

    tool_dedup_title: "Remove Duplicates",
    tool_dedup_desc: "Keeps only unique lines",
    tool_dedup_trim: "Trim spaces",

    tool_sort_title: "Sort",
    tool_sort_desc: "Sorts the list",
    tool_sort_mode: "Mode",
    tool_sort_text: "Text",
    tool_sort_numeric: "Numeric",
    tool_sort_smart: "Smart (Numbers inside)",
    tool_sort_direction: "Direction",
    tool_sort_asc: "Ascending (A-Z)",
    tool_sort_desc: "Descending (Z-A)",
    tool_sort_case: "Ignore case",

    tool_reverse_title: "Reverse",
    tool_reverse_desc: "Reverses the list of lines",

    tool_compare_title: "Compare (Diff)",
    tool_compare_desc: "Compare incoming text with a second list",
    tool_compare_list2: "List for comparison",
    tool_compare_placeholder: "Lines for comparison...",
    tool_compare_delimiter: "List delimiter",
    tool_compare_show: "Show",
    tool_compare_common: "Only common",
    tool_compare_diff: "Only differences (A-B)",
    tool_compare_all: "All with marks",

    tool_duplicates_title: "Find Duplicates",
    tool_duplicates_desc: "Shows only repeating lines",
    tool_duplicates_show_counts: "Show counts",
    tool_duplicates_none: "(No duplicates)",

    tool_filter_title: "Line Filter",
    tool_filter_desc: "Keep/Remove lines by condition",
    tool_filter_query: "Search text",
    tool_filter_contains: "Contains",
    tool_filter_not_contains: "Does not contain",
    tool_filter_starts: "Starts with",
    tool_filter_ends: "Ends with",

    tool_csv_title: "CSV Parser",
    tool_csv_desc: "Convert CSV to text by template",
    tool_csv_delimiter: "CSV Delimiter (; or ,)",
    tool_csv_template: "Template ($1, $2...)",
    tool_csv_skip_header: "Skip header",

    tool_case_title: "Case",
    tool_case_desc: "UPPERCASE, lowercase, Capitalize",
    tool_case_upper: "UPPERCASE",
    tool_case_lower: "lowercase",
    tool_case_cap: "Sentence Case",
    tool_case_word: "Each Word",

    tool_wrapper_title: "Wrapper (Prefix/Suffix)",
    tool_wrapper_desc: "Add text to the beginning/end of each line",
    tool_wrapper_prefix: "Prefix",
    tool_wrapper_suffix: "Suffix",

    tool_trim_title: "Trim",
    tool_trim_desc: "Removes spaces from the edges of each line",
    tool_trim_both: "Both sides",
    tool_trim_left: "Left side",
    tool_trim_right: "Right side",

    tool_ai_cleaner_title: "AI Cleaner",
    tool_ai_cleaner_desc: "Cleanup typography and special characters",
    tool_ai_cleaner_replace: "Replace junk with",

    tool_json_format_title: "JSON Formatting",
    tool_json_format_desc: "Turns text into pretty JSON",
    tool_json_format_indent: "Indent",
    tool_json_format_2spaces: "2 spaces",
    tool_json_format_4spaces: "4 spaces",
    tool_json_format_tab: "Tabulation",
    tool_json_format_minify: "Minify",
    tool_json_format_join: "Join delimiter",
    tool_json_format_empty: "Empty input",

    tool_json_path_title: "Extraction (JSONPath)",
    tool_json_path_desc: "Extracts elements from JSON text (e.g. $.users[*].name)",
    tool_json_path_query: "JSONPath query",
    tool_json_path_input_mode: "Input data",
    tool_json_path_combined: "All lines as one JSON",
    tool_json_path_lines: "Each line as separate JSON",
    tool_json_path_stringify: "Wrap objects in JSON",
    tool_json_path_lib_error: "JSONPath library not loaded! Check internet connection.",
    tool_json_path_parse_error: "JSON parse error: ",
    tool_json_path_error: "JSONPath error: ",

    tool_join_title: "Join Lines",
    tool_join_desc: "Assembles list into a single string",
    tool_join_prefix: "First characters",
    tool_join_last_delimiter: "Last delimiter",
    tool_join_suffix: "Last characters",
    tool_join_and: " and ",

    tool_split_title: "Split String",
    tool_split_desc: "Splits lines by delimiter",

    tool_add_line_title: "Add Line",
    tool_add_line_desc: "Adds lines to the beginning, end of the list and/or between lines",
    tool_add_line_start: "First line",
    tool_add_line_between: "Between lines",
    tool_add_line_end: "Last line",

    tool_template_title: "Templatizer (Nunjucks)",
    tool_template_desc: "Generation by template (body and lines available)",
    tool_template_tpl: "Nunjucks template (body and lines available)",

    tool_js_function_title: "Function (JS)",
    tool_js_function_desc: "Custom JS code for each line processing",
    tool_js_function_code: "Function code (argument 'line')",
    tool_js_function_compilation_error: "Compilation error: ",

    tool_shuffle_title: "Random Shuffle",
    tool_shuffle_desc: "Shuffles lines in random order",
    tool_shuffle_seed: "Seed (number)",

    tool_to_hex_title: "To HEX",
    tool_to_hex_desc: "Convert text to hexadecimal code",
    tool_to_hex_encoding: "Encoding",
    tool_to_hex_format: "Format",
    tool_to_hex_plain: "Plain string (xxyyzz)",
    tool_to_hex_spaced: "With spaces (xx yy zz)",
    tool_to_hex_dump: "Dump (offset + 16 bytes)",
    tool_to_hex_dump_ascii: "Dump + ASCII",
    tool_to_hex_uppercase: "Uppercase letters (A-F)",
    tool_to_hex_error: "Encoding error: ",

    tool_from_hex_title: "From HEX",
    tool_from_hex_desc: "Convert hexadecimal code back to text",
    tool_from_hex_encoding: "Byte encoding",
    tool_from_hex_invalid_chars: "Invalid characters detected in HEX data on line",
    tool_from_hex_incomplete: "Incomplete byte (odd number of characters) on line",
    tool_from_hex_not_found: "HEX data not found. Supported formats: \"xx yy zz\", \"xxyyzz\" or dump \"0000: xx yy zz |ascii|\"",
    tool_from_hex_error: "Decoding error: ",

    tool_encode_title: "Encoding (Base64/URL)",
    tool_encode_desc: "Encoding and decoding (Base64, URL)",
    tool_encode_mode: "Action",
    tool_encode_error: "Error: ",

    tool_hash_title: "Hashing",
    tool_hash_desc: "Calculates CRC32, MD5, SHA-1, SHA-256, SHA-384, SHA-512",
    tool_hash_algorithm: "Algorithm",
    tool_hash_lib_error: "CryptoJS library not loaded! Check internet connection.",

    tool_debug_title: "Debug View",
    tool_debug_desc: "Visualizes invisible characters (spaces, tabs, breaks)",
    tool_debug_spaces: "Show spaces (·)",
    tool_debug_tabs: "Show tabs (→)",
    tool_debug_numbers: "Line numbers",

    // LLM Tool
    tool_llm_title: "AI Assistant (LLM)",
    tool_llm_desc: "Processing text using Large Language Models (Qwen, DeepSeek, etc.)",
    tool_llm_provider: "Provider",
    tool_llm_model: "Model",
    tool_llm_api_key: "API Key",
    tool_llm_system_prompt: "System Prompt",
    tool_llm_prompt_tpl: "User Prompt Template",
    tool_llm_batch_processing: "Batch processing",
    tool_llm_batch_size: "Batch size (lines)",
    tool_llm_manual_run: "Manual Execution",
    tool_llm_run_btn: "Run AI Processing",
    tool_llm_running: "AI is thinking...",
    tool_llm_tokens: "Tokens:",
    tool_llm_waiting_manual: "Waiting for manual run...",
    tool_llm_auth_required: "Authorization required",
    tool_llm_login_qwen: "Login with Qwen",
    tool_llm_oauth_code: "Enter this code at chat.qwen.ai/activate:",
    tool_llm_waiting_auth: "Waiting for authorization...",
    tool_llm_auth_success: "Successfully authorized!",
    tool_llm_stats_tokens: "Tokens used: ",
    tool_llm_stats_prompt: "Prompt: ",
    tool_llm_stats_completion: "Completion: ",
    tool_llm_error: "LLM Error: ",
    tool_llm_locked: "Execution in progress. Pipeline is locked.",

    llm_settings: "LLM Settings",
    llm_proxy_url: "Proxy Base URL",
    llm_proxy_placeholder: "http://127.0.0.1:20000/uuid...",
    run_chain: "Execute"
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANG_EN;
}
