var LANG_EN = {
    app_description: "StringLOM — visual text pipeline. Block chains: Regex, JSON, CSV, sorting. Instant results, 100% in-browser, no server. Drag & drop, private, no installation.",
    menu_title: "Menu",
    home_page: "Home Page",
    download_latest: "Download Latest Release",
    theme_dark: "Dark Theme",
    theme_light: "Light Theme",
    version: "Version:",
    create: "Create",
    create_title: "Create new chain (Alt + N)",
    import: "Import",
    import_title: "Import chain (Alt + I)",
    saved_chains: "Saved Chains",
    toggle_saved: "Collapse/Expand",
    new_chain: "New Chain",
    save: "Save",
    save_title: "Save current chain (Alt + S)",
    share: "Share",
    share_title: "Share chain",
    export: "Export",
    export_title: "Export chain settings (Alt + E)",
    final_result: "Final Result",
    download_final: "Download result",
    copy_final: "Copy result",
    output_delimiter: "Output Delimiter",
    newline: "New Line",
    comma: "Comma",
    semicolon: "Semicolon",
    space: "Space",
    custom: "Custom...",
    custom_placeholder: "Text...",
    select_tool: "Select Tool",
    search_tools: "Search tools (2+ characters)...",
    confirmation: "Confirmation",
    cancel: "Cancel",
    confirm: "Confirm",
    input_data: "Data Input",
    enter_value: "Enter value...",
    ok: "OK",
    attention: "Attention",
    close: "Close",
    delete_chain_confirm: "Are you sure you want to delete the saved chain?",
    switch_chain_confirm: "Switch to another chain? All unsaved changes to the current one will be lost.",
    new_chain_confirm: "Create a new chain? All unsaved changes to the current one will be lost.",
    no_saved_chains: "No saved chains",
    delete: "Delete",
    default_source_text: "Example line\nSecond line\n123",
    block_removed: "Block removed",
    restore_block: "Restore block",
    add_block: "Add block",
    expand_blocks: "Expand blocks",
    collapse_blocks: "Collapse blocks",
    drag_to_move: "Drag to move",
    load_from_file: "Load from file",
    help: "Help",
    add_block_above: "Add block above (Alt + B)",
    add_block_below: "Add block below (Alt + A)",
    remove_block_alt: "Remove block (Alt + Delete)",
    source_placeholder: "Enter text here (or drag file here)...",
    line_delimiter: "Line Delimiter",
    lines_count: "Lines:",
    add_without_closing: "Add without closing",
    created: "Created",
    saved: "Saved",
    exported: "Exported",
    copied: "Copied",
    share_error: "Error creating link",
    copy_clipboard_error: "Failed to copy to clipboard. Use export to file or copy manually.",
    import_prompt: "Paste previously copied chain code (JSON):",
    invalid_chain_format: "Invalid chain format",
    import_error: "Import error: Invalid data format",
    enter_chain_name: "Enter a name for this chain:",
    rename_title: "Click to rename (Alt + R)",
    chain_name_placeholder: "Chain name...",

    // Categories
    cat_search_clean: "Search and Clean",
    cat_remove_filter: "Remove and Filter",
    cat_order_compare: "Order and Compare",
    cat_text_transform: "Text Transformation",
    cat_formats: "Work with Formats",
    cat_assembly_templates: "Assembly and Templates",

    // Tools
    tool_regex_title: "Search and Replace (Regex)",
    tool_regex_desc: "Replace using regular expression",
    tool_regex_long_desc: "This tool is designed for the automatic searching and modification of text fragments based on specified rules. You can use it to process large lists of names, email addresses, or inventory numbers within your system. The main search rule is defined in a special search field where you describe the structure of the required data. If you need not only to find but also to replace the found parts, use the field for specifying a new value. This is very convenient when you need to bring all unique designations in event records to a single standard or hide confidential information. The tool supports the ability to ignore differences between capital and small letters, which significantly expands the search area. For this purpose, a setting is provided that disables sensitivity to character size. If your task consists only of extracting the necessary data, you can enable a mode to save exclusively found matches. In this case, all unnecessary parts of the source text will be discarded, and you will receive a clean list of results. This is useful when forming exports with only the required parts from complex reports. During the replacement process, you can use special references to found groups of characters to rearrange or supplement them. The entire process happens instantly right in the program window without sending data to third-party resources. You can experiment with search rules while immediately seeing the final processing result at the bottom of the window. The tool helps avoid routine manual work when editing hundreds of lines of textual information. Using such an approach guarantees high accuracy and repeatability of your data processing results. It is a reliable assistant for any specialist working with text settings or lists of system incidents.",
    tool_regex_pattern: "Regular Expression",
    tool_regex_replacement: "Replace with ($1, $2...)",
    tool_regex_case: "Case insensitive",
    tool_regex_only_matched: "Only matched",
    tool_regex_empty: "Empty pattern",

    tool_dedup_title: "Remove Duplicates",
    tool_dedup_desc: "Keeps only unique lines",
    tool_dedup_long_desc: "This program block serves to clean lists of repeating elements and leave only unique lines. It is ideally suited for processing lists of usernames, mailing addresses, or device identifiers after merging several data sources. The block's operation begins with an analysis of each line of incoming text to identify exact matches. You can enable a preliminary cleaning of lines from extra spaces at the edges, which will ensure a more accurate comparison. This helps avoid situations where records that look identical at first glance are considered different due to invisible characters at the end or beginning. As a result of the work, you will receive a concise list where each element occurs exactly once. Such a tool is indispensable when preparing clean data for import into other accounting systems or for mailings. It allows you to significantly reduce the volume of processed information by removing unnecessary information noise. The mechanics of the operation are simple and do not require complex settings, providing a fast and predictable outcome. All transformations are performed on the fly, allowing you to immediately see how many extra records were removed from the general flow. The tool preserves the order of the first appearance of unique lines, which may be important for maintaining the sequence of events. Using this function prevents errors associated with multiple processing of the same information. It is a basic but extremely effective way to bring order to any text lists. The program guarantees the safety of your data since all processing takes place exclusively inside your browser. Data cleanliness and uniqueness are the key to the correct operation of any software.",
    tool_dedup_trim: "Trim spaces",

    tool_sort_title: "Sort",
    tool_sort_desc: "Sorts the list",
    tool_sort_long_desc: "This block is intended for ordering lines of text in accordance with the rules and logic you choose. You can use it to build alphabetical lists of employees, sort numerical performance indicators, or order event records by time. The tool offers several different operating modes to achieve the best result depending on the type of your data. The normal text mode simply compares characters with each other, which is suitable for most general tasks. The numeric mode allows for the correct processing of lists with digits so that the number ten comes after the number two, not before it. Smart sorting combines these approaches, correctly processing lines that contain both letters and digits simultaneously. You can choose the direction of ordering, arranging elements from start to finish or in reverse order. A setting is also available to ignore differences between capital and lowercase letters when comparing texts. This allows you to avoid a situation where words starting with the letter A end up in different parts of the list due to different cases. The result of the block's operation is always predictable and helps to quickly navigate through large volumes of information. Well-structured data significantly simplifies the search for needed records and the analysis of the overall picture. The entire process of rebuilding the list occurs instantly after changing any parameter. The tool supports working with regional language features, which guarantees the correct order of letters in the alphabet. Using automatic sorting saves a lot of time compared to manual arrangement of elements. This is an important stage in preparing any reports or system lists for further use.",
    tool_sort_mode: "Mode",
    tool_sort_text: "Text",
    tool_sort_numeric: "Numeric",
    tool_sort_smart: "Smart (Numbers inside)",
    tool_sort_direction: "Direction",
    tool_sort_asc: "Ascending (A-Z)",
    tool_sort_desc: "Descending (Z-A)",
    tool_sort_case: "Ignore case",

    tool_reverse_title: "Reverse",
    tool_reverse_desc: "Reverses the list of lines",
    tool_reverse_long_desc: "This tool performs a simple but useful operation of completely changing the order of lines in your list to the opposite one. It is ideally suited for cases where you need to view the latest events in a record first or reverse the sequence of steps in an instruction. The block's work consists of making the very last line become the first, while the very first moves to the very end. No additional settings are required, as the logic of the action is as transparent and understandable as possible. You simply add this block to your processing chain, and it instantly reverses the current result. This is useful when working with system records that are appended to the end of a file, and you need to see the fresh information at the top. The tool does not change the content of the lines themselves but only rearranges them in the general list. Such an approach guarantees the safety of all data while changing its visual representation. The result of the work is visible immediately, allowing you to quickly assess the necessity of this action in the overall process. The mechanics of the operation are extremely efficient and handle lists of any size almost instantly. You can combine this block with other tools, for example, after sorting, to obtain the desired order. Simplicity of use makes this block accessible even to those who have never dealt with text processing. The absence of control parameters eliminates the possibility of error when configuring the block. This is a reliable way to quickly change the perspective on your textual data. Using list reversal helps in analyzing sequences and identifying patterns in data.",

    tool_compare_title: "Compare (Diff)",
    tool_compare_desc: "Compare incoming text with a second list",
    tool_compare_long_desc: "This block is designed for comparing the main text with a second list of data to identify common elements or differences. You can use it to check lists of permitted addresses, find new users, or remove already processed records. The second list for comparison is entered into a special text field inside the block's settings. For correct separation of elements in the second list, a choice of separator is provided, such as a new line or a comma. The main mechanics of the operation consist of choosing one of three result display modes. You can leave only those lines that are present in both lists simultaneously to find intersections. The difference search mode will show only those elements of the first list that are not in the second data set. A full display mode is also available, where each line is marked with a special symbol indicating its presence or absence in the lists. This allows you to clearly see the entire picture of relationships between two sets of textual information. The tool automatically removes extra spaces at the edges of lines before comparison to increase accuracy. Such an approach excludes errors caused by accidental inaccuracies during manual data entry. The entire matching process takes place on your device, which ensures the confidentiality of the compared lists. The result of the block's work allows you to quickly make decisions based on the analysis of correspondences. The tool is indispensable when preparing updates for data storages or checking access rights. Using automatic comparison guarantees the absence of omissions and errors typical of a human.",
    tool_compare_list2: "List for comparison",
    tool_compare_placeholder: "Lines for comparison...",
    tool_compare_delimiter: "List delimiter",
    tool_compare_show: "Show",
    tool_compare_common: "Only common",
    tool_compare_diff: "Only differences (A-B)",
    tool_compare_all: "All with marks",

    tool_duplicates_title: "Find Duplicates",
    tool_duplicates_desc: "Shows only repeating lines",
    tool_duplicates_long_desc: "This tool helps to quickly detect and display only those lines that occur in your text more than once. It will be useful for system administrators to identify repeating login attempts or errors in configuration files. Instead of removing extra entries, this block, on the contrary, focuses your attention exactly on the problematic repetitions. In the settings, you can enable the display of the count of mentions for each found duplicate line. This allows you to immediately assess the frequency of occurrence of a particular event or the popularity of a certain value. If no repetitions are found, the tool will politely inform you about this with a special notification. The result of the work is a clean list of repeating elements with optional statistics for each of them. You can use this data for further investigation of the reasons for the appearance of redundant information in the system. The mechanics of the block's operation are based on a full scan of the entire incoming data array. Before analysis, the lines undergo preliminary processing to eliminate the influence of accidental spaces. The tool works very quickly even with very long lists, providing the result in fractions of a second. The visual representation of data in this block helps to focus on the most important things. Using the repeat search function is an important step in auditing and checking data integrity. You can easily integrate this block into your processing chain for regular monitoring of text quality. The program ensures full privacy since all calculations are conducted without transferring information to the network.",
    tool_duplicates_show_counts: "Show counts",
    tool_duplicates_none: "(No duplicates)",

    tool_filter_title: "Line Filter",
    tool_filter_desc: "Keep/Remove lines by condition",
    tool_filter_long_desc: "This program block allows you to filter out unnecessary lines from the general text based on a condition or keyword you set. You can use it to isolate only critical errors from a large event record or to search for employees by last name. The main parameter is the search text, which serves as a sample for checking each line. The tool offers several different ways of matching the text with your request. You can choose a simple inclusion mode, where the line remains if it contains the searched word in any of its parts. Options are also available for searching for lines that strictly start or end with a certain set of characters. If you need, on the contrary, to remove everything unnecessary, use the exclusion mode, which will delete all lines with the specified text. The entire filtering process occurs while ignoring the case of letters, which makes the search more flexible and convenient. At the bottom of the block, statistics are displayed on how many lines passed the check and how many were discarded. This helps to control the processing procedure and ensure the correctness of the settings. The result of the work is an updated list containing only the information you are interested in. The tool is indispensable when working with huge arrays of textual data where manual search is impossible. Simplicity of parameter configuration allows you to instantly switch between different filtering conditions. You can sequentially apply several such blocks to create complex data selection conditions. Using an automatic filter significantly increases the speed of working with text reports and lists.",
    tool_filter_query: "Search text",
    tool_filter_contains: "Contains",
    tool_filter_not_contains: "Does not contain",
    tool_filter_starts: "Starts with",
    tool_filter_ends: "Ends with",

    tool_csv_title: "CSV Parser",
    tool_csv_desc: "Convert CSV to text by template",
    tool_csv_long_desc: "This tool is intended for converting data from table formats with separators into ordinary coherent text according to your own template. It is ideally suited for creating beautiful reports from accounting system exports, forming letters, or lists of settings. The main parameter here is the choice of the character that separates columns in your source text, most often a semicolon or a comma. You can configure the block to skip the first line if it contains only column headings. The most interesting part of the work consists of creating a template where you specify exactly how the data from the columns should be located. In the template, special designations are used to insert the content of the first, second, or any other column. For example, you can write a phrase into which the username and their email address from each row of the table will be automatically substituted. The tool takes each line in turn, breaks it into parts, and assembles a new sentence according to your rules. As a result, you receive a list of ready-made texts formed based on structured information. This eliminates the need to manually rewrite data from tables into text documents. The mechanics of the block's operation are very efficient and allow processing thousands of lines in a matter of moments. You immediately see the result of the conversion and can easily adjust the template to achieve the desired look. The tool supports the use of any characters in the template, including punctuation marks and spaces. Using such a converter guarantees uniformity and the absence of typos in all created records. This is a powerful means for automating routine preparation of text documents based on data storages.",
    tool_csv_delimiter: "CSV Delimiter (; or ,)",
    tool_csv_template: "Template ($1, $2...)",
    tool_csv_skip_header: "Skip header",

    tool_case_title: "Case",
    tool_case_desc: "UPPERCASE, lowercase, Capitalize",
    tool_case_long_desc: "This block serves for quickly changing the way letters are written in your text, making them capital or lowercase. You can use it to bring a list of names to a single standard or for preparing headings in documentation. The tool offers four different transformation modes to choose from depending on your current task. The first mode turns absolutely all letters into capital ones, which is often required for highlighting important warnings or codes. The second mode, on the other hand, makes all letters small, which is useful for uniformity of email addresses or system paths. The third option automatically makes the first letter of each sentence large, correcting possible inaccuracies during fast text entry. The fourth mode capitalizes each individual word, which is ideal for formatting names, surnames, or job titles. The mechanics of the block's operation are extremely simple: it takes each line and applies the chosen transformation rule to it. All changes occur instantly, and you immediately see the updated text in the program window. This eliminates the need to manually switch layouts or correct the case in each line individually. The tool correctly works with letters of different alphabets, maintaining the correctness of writing all characters. Using automatic case switching helps make your lists and reports more professional and neat. You can easily cancel or change the chosen mode if the result did not satisfy you. This block is an important element in the chain of preparing texts for publication or entry into data storages. Regular use of such a tool significantly reduces the time for preparing texts for further work. It is a simple and effective way to achieve visual cleanliness and order in any textual information.",
    tool_case_upper: "UPPERCASE",
    tool_case_lower: "lowercase",
    tool_case_cap: "Sentence Case",
    tool_case_word: "Each Word",

    tool_wrapper_title: "Wrapper (Prefix/Suffix)",
    tool_wrapper_desc: "Add text to the beginning/end of each line",
    tool_wrapper_long_desc: "This tool allows for the bulk addition of arbitrary text to the very beginning and the very end of each line in your list. It is very convenient when you need to format a list of words as program variables, add quotes, or special characters for a data storage. The block has two main fields for entry: a prefix for text at the beginning of the line and a suffix for text at the end. You can fill both fields or only one of them depending on your current need. For example, by adding an opening and a closing parenthesis, you will instantly wrap all elements of the list in them. The mechanics of the work consist of the sequential processing of each incoming line and gluing the specified pieces of text to it. This is significantly faster than manually editing each entry in a notebook, especially if there are hundreds or thousands of them. The tool does not change the content of the line itself but only supplements it from the outer sides. You can use any characters, including spaces, punctuation marks, and even special technical marks. The result of the block's work is displayed immediately, allowing for a visual assessment of the correctness of the chosen additions. Such an approach guarantees that not a single line will be missed and all of them will receive the same formatting. The wrapper block is often used in combination with other tools for preparing data for import into other systems. Simplicity of settings makes it accessible and understandable for any user without special training. Using this tool minimizes the risk of errors during bulk modification of text lines. You can infinitely experiment with different variants of text framing, achieving the desired visual or technical effect. This is a reliable means for fast preparation of data according to any system requirements.",
    tool_wrapper_prefix: "Prefix",
    tool_wrapper_suffix: "Suffix",

    tool_trim_title: "Trim",
    tool_trim_desc: "Removes spaces from the edges of each line",
    tool_trim_long_desc: "This program block is designed for the automatic cleaning of the edges of text lines from extra invisible characters, such as spaces or tabs. Often when copying data from tables or other programs, accidental indents appear in the text, which can interfere with correct processing. The tool offers three operating modes for the most accurate control over the data cleaning process. You can choose to remove spaces simultaneously from both sides of the line to obtain the cleanest possible result. Options are also available for cleaning only the left side to remove initial indents, or only the right side. The mechanics of the block's operation consist of scanning the edges of each line and removing all characters that are not letters, digits, or punctuation marks. At the bottom of the block, you will be able to see statistics on the number of lines in which changes were made. This allows for an assessment of the overall contamination of the source data and ensures the effectiveness of the tool's work. The result of the block's work is a neat and even list, ready for further transformations or comparison. Using space trimming is a mandatory step before sorting or searching for duplicates to increase the accuracy of these operations. The tool works lightning fast and does not require complex parameter configuration. You simply choose the desired mode, and the program takes all the routine work upon itself. Data cleanliness at the entry guarantees the absence of errors in the operation of the entire subsequent chain of tools. A well-prepared text significantly simplifies life for any specialist working with information. You can be sure that not a single accidental space will spoil your further work with this list. This is a basic means for maintaining data hygiene in any text projects.",
    tool_trim_both: "Both sides",
    tool_trim_left: "Left side",
    tool_trim_right: "Right side",

    tool_ai_cleaner_title: "AI Cleaner",
    tool_ai_cleaner_desc: "Cleanup typography and special characters",
    tool_ai_cleaner_long_desc: "This tool serves for the intelligent cleaning of your text from junk, typographical errors, and rare special characters. It is especially useful when processing texts copied from different sources with different formatting and encodings. The block automatically replaces various types of long dashes and quotes with standard characters accepted in computer systems. In addition, it is capable of removing any characters that do not belong to letters, digits, or standard punctuation marks. In the settings, you can specify a specific text or character that will replace all found junk in the lines. This allows not only removing unnecessary things but also replacing suspicious fragments with an empty string or a space. The mechanics of the block's operation are based on strict rules for filtering each individual character in all lines of text. As a result, you receive a maximally standardized and clean text, devoid of strange icons and invisible interferences. The tool outputs information on exactly how many characters were removed or replaced during the processing. This helps to control the depth of cleaning and notice in time if important data was removed. Using such a cleaner significantly simplifies further automated processing of texts by other software means. The block helps avoid errors when importing data into systems that are sensitive to non-standard encodings. The entire process takes place inside the program, ensuring the security and privacy of your information. It is a reliable way to bring diverse text data to a single form understandable to all systems. You can use this block as a universal filter for any incoming stream of textual information. Regular application of cleaning guarantees high quality of your reports and lists.",
    tool_ai_cleaner_replace: "Replace junk with",

    tool_json_format_title: "JSON Formatting",
    tool_json_format_desc: "Turns text into pretty JSON",
    tool_json_format_long_desc: "This block is designed to turn chaotic and hard-to-read technical text into a beautifully formatted and understandable data structure. It works with a special format that is often used for exchanging information between different programs and websites. The main task of the tool is to set the correct indents and line breaks so that the data hierarchy becomes clear to a person. You can independently choose the indent size, using two or four spaces, or even a tab character for formatting. A reverse mode is also provided, which compresses the text as much as possible, removing all extra spaces and breaks to reduce data volume. Another important parameter is the choice of a character for merging several lines into one before starting the processing procedure. This allows for gathering scattered pieces of information into a single data block for correct analysis by the program. The tool automatically checks the correctness of the text structure and reports errors if the data is damaged or incomplete. The result of the work is a neatly formatted list of parameters where each element is in its place. Such a representation of data significantly simplifies the search for errors in program settings and the analysis of complex reports. The mechanics of the block's operation guarantee the preservation of all values in their original form without distortion. Using automatic formatting saves time that is usually spent on manual arrangement of brackets and indents. This is an indispensable assistant for those who often work with system configuration files or program request results. Beautifully formatted data is easier to read, check, and pass to colleagues for joint work. The program provides fast and accurate text conversion of any volume right in the browser window. You can instantly switch between compact and expanded views of data with a single mouse movement.",
    tool_json_format_indent: "Indent",
    tool_json_format_2spaces: "2 spaces",
    tool_json_format_4spaces: "4 spaces",
    tool_json_format_tab: "Tabulation",
    tool_json_format_minify: "Minify",
    tool_json_format_join: "Join delimiter",
    tool_json_format_empty: "Empty input",

    tool_json_path_title: "Extraction (JSONPath)",
    tool_json_path_desc: "Extracts elements from JSON text (e.g. $.users[*].name)",
    tool_json_path_long_desc: "This tool allows for the precise extraction of the pieces of information you need from complex and voluminous technical data structures. Imagine that you have a huge list of users with many parameters, and you need only their names or email addresses. With the help of special request rules, you specify the path to the elements you are interested in within the general array of information. The block supports two modes of processing incoming data depending on how they are represented in the source text. In the first mode, all lines are considered as one large unified structure for searching for the necessary fragments. In the second mode, the program treats each individual line as an independent object and applies the search rule to each of them in turn. You can also configure the method of merging data and choose whether to turn found complex objects back into textual form. If errors in the data structure occur during the processing, the tool will definitely inform you about this in the statistics block. The result of the work is a clean list of only those values that match your request. This eliminates the need to manually browse through thousands of lines of code in search of the needed information. The mechanics of the block's operation are based on generally accepted standards for searching in data structures, which ensures predictability of the result. You can easily form summaries from complex reports or prepare data for other processing tools. Using this block significantly increases the efficiency of working with modern information storage formats. All processing happens instantly right in your browser, keeping the data secure. This is a powerful means for any analyst or system administrator working with large volumes of structured information. You will get exactly the data you need without unnecessary information noise and routine labor.",
    tool_json_path_query: "JSONPath query",
    tool_json_path_input_mode: "Input data",
    tool_json_path_combined: "All lines as one JSON",
    tool_json_path_lines: "Each line as separate JSON",
    tool_json_path_stringify: "Wrap objects in JSON",
    tool_json_path_lib_error: "JSONPath library not loaded! Check internet connection.",
    tool_json_path_parse_error: "JSON parse error: ",
    tool_json_path_error: "JSONPath error: ",

    tool_join_title: "Join Lines",
    tool_join_desc: "Assembles list into a single string",
    tool_join_long_desc: "This program block is designed for assembling individual lines of your list into one common long line with specified separators. This is very convenient when you need to turn a list of words into a sentence separated by commas or create a single line of parameters for another program. The tool offers flexible configuration of exactly how your text elements will be glued together. You can specify special text that will be added to the very end and to the beginning of the resulting common line. For separating elements among themselves, a main separator is used, for example, a space or a semicolon. A feature of the block is the ability to set a separate separator for the very last element in the list. This allows for creating natural phrases where a conjunction will stand before the last word instead of a comma. The mechanics of the work consist of the sequential connection of all lines taking into account the formatting rules you chose. The result of the work is a single line containing all the information from the source list in a compact form. The tool automatically adjusts to the number of lines, correctly processing even lists of one element. Such an approach allows for easy preparation of data for insertion into documents or for use as command requests. Simplicity of parameter control makes this block very clear and convenient for daily use. Using the line merging function helps save space and present information in a more readable format. You can quickly create a ready-made list for insertion into an email or a report in just a couple of clicks. The program guarantees that all elements will be connected strictly according to your rules without omissions or errors. This is a reliable tool for finalizing the processing of any data lists.",
    tool_join_prefix: "First characters",
    tool_join_last_delimiter: "Last delimiter",
    tool_join_suffix: "Last characters",
    tool_join_and: " and ",

    tool_split_title: "Split String",
    tool_split_desc: "Splits lines by delimiter",
    tool_split_long_desc: "This tool performs the operation opposite to merging, turning one or several lines into a long list of elements. It is ideally suited for cases where you have a line of words separated by commas and you want each word to stand on its own separate line. The main and only parameter here is the choice of the separator character by which the program will cut your text. You can use standard marks, such as a comma, a semicolon, or a space, and also set any unique character of your own. The mechanics of the block's operation consist of searching for all specified separators and creating a new line at the place of each such mark. As a result, instead of dense text, you receive an ordered column of data, which is much more convenient to analyze or sort. The tool automatically counts how many new lines were obtained in total and outputs this number in the statistics block. This is very useful when parsing complex system paths, parameter lists, or data copied from table cells. The separation process occurs instantly, allowing you to immediately proceed to the next stage of processing the obtained list. The split block is often the initial link in a chain of tools, preparing data for filtering or removing duplicates. The absence of extra settings makes working with it simple and error-free for any level of preparation. Using this tool guarantees neat separation of information without losing important text fragments. You can be sure of the accuracy of the result since the program strictly follows the separation rule you set. The number of lines at the output can significantly increase, which will clearly show the volume of your data. This is a basic block for turning solid text into a structured list of elements.",

    tool_add_line_title: "Add Line",
    tool_add_line_desc: "Adds lines to the beginning, end of the list and/or between lines",
    tool_add_line_long_desc: "This block allows for supplementing your list with new lines in specific places: at the very beginning, at the very end, or between each existing line. It is very useful when you need to add headings to a list, insert separation lines, or empty lines to improve readability. The tool has three independent fields for entering the text you want to add to the corresponding positions. You can fill any of them or all at once, creating the desired structure for your text document. Text from the field for the start of the list will be added once before the first line of source data. The content of the field for intervals will be inserted after each line of your list except for the very last one. The text for the end of the list will, accordingly, appear at the very final of the total result. The mechanics of the work consist of simple and predictable appending of your phrases to the general array of information. This is significantly more convenient and faster than manually inserting empty lines or marks in a text editor. The result of the work is visible immediately, which allows for easy adjustment of the added lines to achieve the ideal look. The tool does not analyze the content of your data but only expands the list according to the specified rules. Such an approach makes it a universal assistant for formatting any text reports or task lists. Using this block helps give your data a finished and professional look without extra effort. You can use this tool to create complex text structures simply by combining different entry fields. The program ensures neat and uniform addition of lines throughout the document. This is an excellent way to structure information for a presentation or further processing.",
    tool_add_line_start: "First line",
    tool_add_line_between: "Between lines",
    tool_add_line_end: "Last line",

    tool_template_title: "Templatizer (Nunjucks)",
    tool_template_desc: "Generation by template (body and lines available)",
    tool_template_long_desc: "This tool is intended for creating complex text documents and reports based on your data list and a special sample. It allows for turning a simple set of lines into full-fledged program code, an HTML page, or a detailed letter. You create a template in which you use special commands to insert data from your list into the required places. The tool supports cycles, allowing for the multiple repetition of certain parts of text for each line from your set. This opens up huge opportunities for automating the creation of same-type documents with different data. The mechanics of the work are based on the use of a popular and powerful template language that understands conditions and logical rules. For example, you can output information differently depending on the content of a line or its sequence number. As a result of the block's work, you receive a ready-made structured text formed strictly according to your rules. This eliminates the need to manually copy and paste data into complex text forms. The statistics block will show the total length of the resulting text, helping to control the volume of the final document. If an error is made in your template, the program will definitely point to it for quick correction. The tool is ideally suited for system administrators and developers who need to quickly generate configurations or documentation. All the magic of turning data into text happens right in your browser without using external resources. You can create an unlimited number of formatting variants for the same source data. This is a professional means for turning raw information into ready-to-use documents. Your work will become much more efficient thanks to the automation of the text formation process.",
    tool_template_tpl: "Nunjucks template (body and lines available)",

    tool_js_function_title: "Function (JS)",
    tool_js_function_desc: "Custom JS code for each line processing",
    tool_js_function_long_desc: "This tool provides almost unlimited possibilities for text processing by writing a small fragment of code in a popular programming language. It is intended for those situations where standard blocks are not enough and it is required to implement your own unique transformation logic for each line. You enter processing rules in a special field where each line of your list is represented as a variable. The tool applies your code to each line in turn, allowing for changing its content, conducting complex calculations, or changing the structure. For example, you can write a rule for extracting certain characters, changing encoding, or performing mathematical operations with numbers in the text. The mechanics of the block's operation ensure the isolation of your code for security, performing all actions exclusively inside the program. If a syntax error is made in the written rule, the statistics block will immediately inform you about this for making corrections. You can see the result of processing each line in real time, which allows for quick debugging of your logic. This tool is a powerful means for advanced users wishing to fully control the data transformation process. It allows for combining complex conditions and algorithms in one place without the need to use external editors. The result of the work is a completely changed list of lines according to your individual algorithm. Using this block makes your data processing chain maximally flexible and adaptive to any tasks. You can save your developments and use them repeatedly for solving similar automation tasks. This is the highest degree of control over textual information in your hands. The program guarantees the stability of your code execution within the specified processing parameters.",
    tool_js_function_code: "Function code (argument 'line')",
    tool_js_function_compilation_error: "Compilation error: ",

    tool_shuffle_title: "Random Shuffle",
    tool_shuffle_desc: "Shuffles lines in random order",
    tool_shuffle_long_desc: "This program block is intended for shuffling the lines of your list in an absolutely random, unpredictable order. You can use it to create random testing queues, shuffle answer choices, or for anonymizing the order of entries in records. The main parameter of the block is a special numeric value that serves as a seed for the random number generator. This allows you to obtain the same shuffling variant when using the same number, which is important for repeatability of results. If you leave the field empty or press the update button, the program itself will choose a new random number for the current session. The mechanics of the block's work guarantee that each line will remain in the list but will change its position to a new one. As a result, you receive the same data set but in a completely different, chaotic arrangement. The tool works instantly even with very large lists, providing high-quality shuffling of elements. Such an approach excludes any bias when choosing the order of lines by a human. The block does not have complex settings, which makes its use as simple and understandable as possible. You immediately see the new line order and can easily generate another sequence with one click. This is an excellent way to introduce an element of randomness into the processing of your textual data for various system tasks. Using automatic shuffling saves time and guarantees fairness in the distribution of elements in the list. You can use the obtained random order for conducting fair draws or distributing tasks among employees. The program ensures high speed of work and full unpredictability of each new variant of line rearrangement. Your information remains intact; only its visual representation changes.",
    tool_shuffle_seed: "Seed (number)",

    tool_to_hex_title: "To HEX",
    tool_to_hex_desc: "Convert text to hexadecimal code",
    tool_to_hex_long_desc: "This tool turns your text into a sequence of special codes that are directly understandable to computer equipment. Each letter or symbol is converted into a unique number in the hexadecimal numeral system, which is often used for low-level data analysis. The block offers a choice of several different encodings, such as modern world standards or old system character tables. You can choose a convenient result display format: a solid line, separated by spaces, or in the form of a detailed technical report. In the technical report mode, the text is broken into blocks of sixteen bytes with an indication of their address in memory and visual confirmation. The ability to enable a mode for displaying letter equivalents next to the codes is also available to simplify the search for the needed information. To improve readability, you can switch the case of letters in the codes between capital and lowercase. The mechanics of the work consist of the sequential encoding of each sign according to the chosen rule and its representation in digital form. This is indispensable for programmers and security specialists when studying the structure of files or data transmitted over the network. The tool correctly handles even complex symbols that may be displayed incorrectly in regular editors. The entire conversion process occurs instantly, allowing for quickly obtaining a digital snapshot of your text. Using this block guarantees an accurate representation of data in the form in which the computer system sees it. You can use this data for deep analysis or for insertion into technical documentation for your project. This is a professional means for those who want to look under the hood of textual information and understand its real structure. The program ensures high accuracy and support for many data representation standards.",
    tool_to_hex_encoding: "Encoding",
    tool_to_hex_format: "Format",
    tool_to_hex_plain: "Plain string (xxyyzz)",
    tool_to_hex_spaced: "With spaces (xx yy zz)",
    tool_to_hex_dump: "Dump (offset + 16 bytes)",
    tool_to_hex_dump_ascii: "Dump + ASCII",
    tool_to_hex_uppercase: "Uppercase letters (A-F)",
    tool_to_hex_error: "Encoding error: ",

    tool_from_hex_title: "From HEX",
    tool_from_hex_desc: "Convert hexadecimal code back to text",
    tool_from_hex_long_desc: "This program block performs the reverse operation, turning hexadecimal numeric codes back into human-understandable text. You can use it to decipher system records, analyze data from memory, or restore information from technical reports. The main parameter is the choice of encoding that was used when creating these codes so that letters and symbols are displayed correctly. The tool is very smart and supports various input data formats: from simple sequences of numbers to complex reports with addresses and marks. The program automatically cleans the incoming text from extra spaces, headings, and service characters before starting decoding. If errors or invalid signs are found in the codes, the statistics block will immediately point to the problematic line. The mechanics of the work consist of converting every two characters of the code into one byte of information and then assembling entire words from them. This eliminates the need to manually translate digits into letters according to character tables. The result of the work is the restored source text, divided into lines for ease of reading. The tool ensures high accuracy of deciphering even in the presence of extra technical information in the codes. You can easily experiment with different encodings if the first result turned out to be unreadable. Using this block significantly speeds up work on analyzing low-level data and restoring information. All processing occurs securely inside your browser. You will receive a clean and understandable text even from the most confusing sets of technical digits. This is a reliable bridge between machine code and human perception of information.",
    tool_from_hex_encoding: "Byte encoding",
    tool_from_hex_invalid_chars: "Invalid characters detected in HEX data on line",
    tool_from_hex_incomplete: "Incomplete byte (odd number of characters) on line",
    tool_from_hex_not_found: "HEX data not found. Supported formats: \"xx yy zz\", \"xxyyzz\" or dump \"0000: xx yy zz |ascii|\"",
    tool_from_hex_error: "Decoding error: ",

    tool_encode_title: "Encoding (Base64/URL)",
    tool_encode_desc: "Encoding and decoding (Base64, URL)",
    tool_encode_long_desc: "This tool is designed for converting your text into special formats that are safe for transmission over the internet or storage in data storages. It supports two of the most popular information processing methods: Base64 and URL encoding. The first method turns any text into a set of standard Latin letters and digits, which is often used for transmitting attachments in emails or hiding data. The second method replaces special characters and spaces with codes using percentages so that links to websites work correctly and without errors. In the block's settings, you choose the desired action: encoding to protect the text or decoding to return to the original look. The mechanics of the work are based on standard algorithms that guarantee compatibility of the result with all modern systems. If an error occurs during the processing (for example, when attempting to decipher incorrect data), the tool will report this in the list of results. The entire conversion process occurs lightning fast, allowing for the processing of entire lists of lines at once. This eliminates the need to use scattered online services and ensures the confidentiality of your information. The result of the block's work is clean text in the chosen format, ready for use in your projects. Using this tool is an important step when preparing data for web development or system integration. Simplicity of switching between modes makes the block very convenient for quick verification and correction of different encoding formats. You can be sure that your data will be transmitted without distortion and loss to any point of the global network. This is a reliable means for ensuring compatibility of your textual data with any external standards. Regular use of such a converter helps avoid many problems with displaying special characters. You receive a guaranteed correct result suitable for any network protocols.",
    tool_encode_mode: "Action",
    tool_encode_error: "Error: ",

    tool_hash_title: "Hashing",
    tool_hash_desc: "Calculates CRC32, MD5, SHA-1, SHA-256, SHA-384, SHA-512",
    tool_hash_long_desc: "This tool serves for creating unique digital fingerprints of your text using special mathematical algorithms. Such a fingerprint allows for uniquely identifying a data line without disclosing its content, which is critically important for security and checking integrity. You can use this block for generating checksums of files, creating secure keys, or checking passwords. The tool offers a wide choice of different algorithms: from fast and simple to maximally reliable and modern ones. The mechanics of the work consist of applying the chosen mathematical function to each line of your list individually. As a result, for each data element, you receive a fixed sequence of characters that will change beyond recognition even with the change of one letter in the source text. This makes hashing an ideal means for detecting any, even the most insignificant, changes in information. The statistics block will inform you about the progress of operations and warn if additional libraries are required for work. All calculations are conducted locally on your computer, which guarantees absolute privacy of your source data. Obtained fingerprints cannot be turned back into text, which is an important property for protecting confidential information. The tool works very quickly, allowing for instantly obtaining results for large lists of lines. Using this block is standard practice when auditing system security and developing reliable software. You can be sure that your data is under the reliable protection of modern cryptographic methods. The program ensures accuracy and repeatability of hash codes for any textual information. It is your personal tool for ensuring digital hygiene and data security.",
    tool_hash_algorithm: "Algorithm",
    tool_hash_lib_error: "CryptoJS library not loaded! Check internet connection.",

    tool_debug_title: "Debug View",
    tool_debug_desc: "Visualizes invisible characters (spaces, tabs, breaks)",
    tool_debug_long_desc: "This special tool is intended for visualizing invisible characters and detailed study of the structure of your text. It is indispensable in cases where the text looks correct but programs output errors due to hidden spaces, tabs, or incorrect line breaks. The block replaces all invisible signs with special graphic symbols that clearly show their presence and type. You can separately enable and disable the display of dots for spaces, arrows for tab signs, and special marks for line endings. In addition, the tool allows for adding line numbering, which significantly facilitates the search for problematic places in large documents. The mechanics of the block's work consist of creating a temporary visual representation of your text while preserving its source content. In the statistics block, a detailed report is output on the number of found spaces and tabs in the entire data array. This helps to quickly assess text quality and make a decision on the necessity of its cleaning. The debugging result is displayed in a convenient preview window, where each character type is highlighted with its own color for better perception. You can use this tool as a final check before saving an important configuration or sending data to another system. Simplicity of settings allows for instantly switching between different visualization modes. Using this block helps avoid annoying errors caused by the human factor or the specifics of copying texts between different editors. Clean and correctly structured text is the key to the successful operation of any information system. The program provides you with a powerful magnifying glass for the most thorough analysis of every letter in your data. You will receive a full understanding of the inner life of your text and will be able to correct all hidden flaws.",
    tool_debug_spaces: "Show spaces (·)",
    tool_debug_tabs: "Show tabs (→)",
    tool_debug_numbers: "Line numbers"
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANG_EN;
}
